namespace GlossaryTrainer.Models;

internal static class GlossaryRepo
{
    //new ("Section 4, unit 36 - Talk about school", [
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),

    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //new("", ["", ""]),
    //]),
    public static List<Glossary> Load()
    =>
    [
        new("All", []),

      new ("Section 4, unit 36 - Talk about school", [
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            new("“what kind of / what sort of”", ["どういう"]),
            new("“word / language / expression / speech”", ["ことば", "言葉"]),
            new("meaning / significance", ["いみ", "意味"]),
            new("“to pull” / “to draw” / “to subtract” (core idea: pulling something toward yourself)", ["だします", "引きます"]),
            new("“during an exam / while an exam is in progress”", ["しけんちゅう", "試験中"]),
            new("“to memorize / to learn / to remember”", ["おぼえます", "覚えます"]),
            new("“in the middle of studying / studying” (not なか)", ["べんきょうちゅう", "勉強中"]),
            new("improvement / progress in skill", ["じょうたつ", "上達"]),
            new("beginner", ["しょしんしゃ", "初心者"]),
            new("“like that (over there)” / “in that way (far away)” (refers to something far from both speaker and listener, or as a realization/exclamation.)", ["ああ"]),
            new("“like that” / “in that way” / “I hear that / is that so?” (refers to something close to the listener or what the listener just said)", ["そう"]),
            new("“like this” / “in this way” / “such” (refers to something close to the speaker’s way or situation)", ["こう"]),
            new("(I / someone) starts / will start / begin (something)　(someone actively starts something, there is a clear agent (doer)) (transitive verb)", ["はじめます", "始めます"]),
            new("will begin / starts / is beginning　(something starts by itself, an event begins, a situation enters its starting phase) (intransitive verb)", ["はじまります", "始まります"]),
            new("“ends” / “will end” / “is over” (ます form)", ["おわります", "終わります"]),
            new("end / conclusion / finish", ["おわり", "終わり"]),
            //
            new("School has already begun / is already in session.", ["学校はもう始まっています", "学校はもう始まりました", "もう学校は始まっています", "もう学校は始まりました"]),
            new("Classes have already begun / are already in session.", ["授業はもう始まっています", "授業はもう始まりました", "もう授業は始まっています", "もう授業は始まりました"]),
            new("Has the homework already been finished?", ["宿題はもう終わりましたか", "もう宿題は終わりましたか"]),
            new("(You) write it like this", ["こう書きます"]),
            new("(You) read it like this", ["こう読みます"]),
            new("(I'm) still a beginner.", ["まだ初心者です"]),
            new("(I'm) still studying / learning", ["まだ勉強中です"]),
            new("(I'm) not good yet", ["まだ上手ではありません", "まだ上手じゃありません", "まだ上手ではないです", "まだ上手じゃないです", "まだ下手です"]),
            new("(I'm) improving / (My) skills are getting better", ["上達しています"]),
            new("Isn't that difficult?　(that = something already mentioned)", ["それは難しくないですか", "それは難しくありませんか"]),
            new("The test yesterday was not easy at all.", ["昨日のテストは全然簡単じゃなかったです", "昨日のテストは全然簡単ではありませんでした"]),
            new("Look at this.", ["これを見て", "これ見て"]),
            new("Do (you) remember?", ["覚えていますか"]),
            new("(I) have not been looking at other students’ tests", ["他の学生のテストを見てはいません", "他の学生のテストは見ていません", "他の学生のテストを見ていません", "他の学生のテストを見ていないです", "他の学生のテストは見ていないです", "他の学生のテストを見てないです", "他の学生のテストは見てないです", "他の学生のテストを見てはいないです"]),
          
            new("(You) cannot look at other students' tests.", ["他の学生のテストを見てはいけません", "他の学生のテストを見てはだめです", "他の学生のテストを見てはいけないです"]),
            new("(You) cannot look at the textbook during the exam (prohibition (rule))", ["試験中は教科書を見てはいけません", "試験中に教科書を見てはいけません", "試験中は教科書を見てはいけないです", "試験中は教科書を見てはだめです"]),
            new("How do (you) write this kanji? (simple skill question (writing, reading, saying))", ["この漢字はどう書きますか", "この漢字をどう書きますか"]),
            new("What does it mean?", ["どういう意味ですか"]),
            new("I don't understand the meaning.", ["意味が分かりません"]),
            new("It has meaning.", ["意味があります"]),
            new("What is the meaning of this kanji?", ["この漢字の意味は何ですか"]),
            new("(I) don't understand the meaning of that word. (that word you just used)", ["その言葉の意味が分かりません"]),
            new("Let's remember the meaning of the word.", ["言葉の意味を覚えましょう"]),
            new("Please teach me the meaning of this kanji.", ["この漢字の意味を教えてください"]),
            new("I looked up that word in a dictionary right away. (the word that just came across)", ["その言葉をすぐに辞書で引きました", "その言葉はすぐに辞書で引きました", "その言葉をすぐ辞書で引きました", "すぐにその言葉を辞書で引きました", "すぐにその言葉は辞書で引きました", "すぐその言葉を辞書で引きました"]),
            new("Please tell me (your) name. (honorific)", ["お名前を教えてください"]),
            new("(I) will memorize the meaning of the kanji.", ["漢字の意味を覚えます"]),
            new("This word has a lot of meanings.", ["この言葉はたくさんの意味があります", "この言葉はたくさん意味があります", "この言葉にはたくさんの意味があります", "この言葉は色々な意味があります", "この言葉は多くの意味を持っています"]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
    ]),

        new("Section 4, unit 35 - Describe nature", [
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            new("'inside the store / in-store' (more formal than 店の中)", ["てんない", "店内"]),
            new("horse", ["うま", "馬"]),
            new("cow", ["うし", "牛"]),
            new("bear", ["くま", "熊"]),
            new("deer", ["しか", "鹿"]),
            new("fox", ["キツネ", "狐"]),
            new("pigeon / dove", ["鳩", "ハト"]),
            new("voice / sound of a person or animal", ["こえ", "声"]),
            new("counter for small to medium-sized animals", ["ひき", "匹"]),
            new("to fly", ["とびます", "飛びます"]),
            new("pond", ["いけ", "池"]),
            new("(animals) make a sound / cry / chirp / bark", ["なきます", "鳴きます"]),
            new("to climb (something physically), to go up / move upward (general), to rise / ascend (formal, abstract, or natural phenomena)", ["のぼります", "登ります"]),
            new("(flowers) bloom / will bloom", ["さきます", "咲きます"]),


            new("In spring many flowers bloom in the garden. (contrast/emphasis on spring, ます form)", ["春にはたくさんの花が庭に咲きます", "春になると、庭にたくさんの花が咲きます", "春、庭にたくさんの花が咲きます", "春には庭にたくさんの花が咲きます", "庭には春になるとたくさんの花が咲きます", "春には庭にたくさんの花が咲いています", "春には多くの花が庭に咲きます", "春になると、庭に多くの花が咲きます", "春、庭に多くの花が咲きます", "春には庭に多くの花が咲きます", "庭には春になると多くの花が咲きます", "春には庭に多くの花が咲いています"]),
            new("(The/A) boy is (in the state of) swimming in the sea.", ["男の子が海で泳いでいます", "男の子は海で泳いでいます"]),
            new("(The/A) monkey was born in Tokyo.", ["猿は東京で生まれました", "猿が東京で生まれました", "東京で猿が生まれました"]),
            new("There are a lot of fish in the pond.", ["池に魚がたくさんいます", "魚が池にたくさんいます", "池には魚がたくさんいます", "池にはたくさんの魚がいます", "池にたくさんの魚がいます", "池には魚が多いです"]),
            new("Please climb that mountain (over there).", ["あの山に登ってください", "あの山を登ってください"]),
            new("Yesterday (I) climbed a mountain.", ["昨日山に登りました", "昨日は山に登りました", "昨日山を登りました", "昨日は山を登りました"]),
            new("Are there yellow flowers blooming in the garden? (ている form)", ["庭に黄色い花が咲いていますか",  "庭には黄色い花が咲いていますか", "庭で黄色い花が咲いていますか"]),
            new("(I) swim in the river in the summer.", ["夏は川で泳ぎます"]),
            new("A plane was (in the state of) flying in the sky.", ["飛行機が空を飛んでいました", "飛行機は空を飛んでいました"]),
            new("Bird(s) are chirping in the garden. (ている form)", ["鳥が庭で鳴いています", "鳥は庭で鳴いています", "庭で鳥が鳴いています"]),
            new("Please be quiet.", ["静かにしてください"]),
            new("It is quiet on that mountain (over there).", ["あの山の中は静かです"]),
            new("(My) little sister is quiet at school.", ["妹は学校で静かです", "学校で妹が静かです"]),
            new("The pigeon is (in the state of) flying.", ["鳩が飛んでいます", "鳩は飛んでいます"]),
            new("Birds fly in the sky. (ます form)", ["鳥は空を飛びます", "鳥が空を飛びます", "空を鳥が飛びます"]),
            new("A person rode a horse.", ["人が馬に乗りました", "人は馬に乗りました"]),
            new("In winter(,) flowers are not blooming. (ている form)", ["冬は花が咲いていません"]),
            new("Three dogs are barking in the store. (ている form)", ["店で三匹の犬が鳴いています", "三匹の犬が店で鳴いています"]),
            new("There are few deer in the zoo.", ["動物園に鹿が少しいます", "動物園には鹿が少しいます"]),
            new("A cow is standing over there. (ている form)", ["牛はあそこで立っています", "牛があそこで立っています", "あそこで牛が立っています", "あそこで牛は立っています"]),
            ]),

        new("Section 4, unit 34 - Discuss belongings", [
            new("gently / softly / quietly / carefully (so as not to disturb or make noise)", ["そっと"]),
            new("mobile phone", ["けいたいでんわ", "携帯電話"]),
            new("I will turn off / erase / delete / extinguish", ["けします", "消します"]),
            new("I will make an effort / I will strive / I will do my best (used in formal speech, writing, business, reports)", ["つとめます", "勤めます"]),
            new("一台", ["いちだい"], true),
            new("二組", ["ふたくみ"], true),
            new("一組", ["ひとくみ"], true),
            new("gloves (any kind of gloves)", ["てぶくろ", "手袋"]),

            new("counter for machines, vehicles, and large equipment", ["だい", "台"]),
            new("counter for matched/symmetrical pairs, “two that belong together” (e.g., gloves)", ["そう", "双"]),
            new("counter for things grouped together as a unit (school class, pair (like couple, gloves), a set)", ["くみ", "組"]),
            new("counter for pairs of footwear (socks, shoes, slippers, anything worn on feet)", ["そく", "足"]),

            new("gray/grey (ash color)", ["はい色", "灰色"]),
            new("Loose / not tight, Relaxed / not strict (rules, attitude), Weak / mild (strength, effect)", ["ゆるい"]),
            new("Tight / too small, Hard / tough / demanding, Strong / intense (effects, tone, etc.)", ["きつい"]),

            new("I wear summer clothes.", ["夏服を着ます", "夏の服を着ます"]),
            new("These shoes are tight.", ["この靴はきついです"]),
            new("I bought two pairs of socks.", ["靴下を二足買いました"]),
            new("The clothes are not loose.", ["服はゆるくないです", "服がゆるくないです", "服はゆるくありません"]),
            new("I bought two pairs of gloves.", ["手袋を二組買いました", "手袋を二双買いました"]),
            new("I woke up early in the morning.", ["朝早く起きました", "朝は早く起きました"]),
            new("I turned off the TV.", ["テレビを消しました"]),
            new("Please close the door slowly.", ["ドアをゆっくり閉めてください", "ゆっくりドアを閉めてください", "ドアをそっと閉めてください", "そっとドアを閉めてください"]),
            new("Is she waiting for a bus?", ["彼女はバスを待っていますか"]),
            new("It is cool in summer, and cold in winter.", ["夏は涼しく、冬は寒いです"]),
            new("Please sit on the chair and wait.", ["椅子に座って待ってください", "椅子にお座りになってお待ちください", "椅子に座って待っていてください", "椅子に座って待っててください"]),
            new("(I) will sit on a chair and wait.", ["椅子に座って待ちます"]),
            new("(I) do not have it. (possession)", ["持っていません", "持っていないです"]),
            new("(I) have three refrigerators. (possession)", ["冷蔵庫を三台持っています", "冷蔵庫は三台持っています", "三台の冷蔵庫を持っています", "三台の冷蔵庫は持っています", "冷蔵庫を三台持ってる"]),
            new("How much is one pair of gloves?", ["手袋は一組いくらですか", "一組の手袋はいくらですか"]),
            new("Spring has come./Spring has arrived.", ["春が来ました"]),
            new("How many beds are there?", ["ベッドは何台ありますか", "ベッドはいくつありますか"]),
            ]),

        new("Section 4, unit 33 - Discuss weather", [
            new("direction / way (direction (“that side”), comparison or preference (“A side” instead of B))", ["ほう", "方"]),
            new("corner / edge / sharp point (A physical edge or point where surfaces meet) (sharp geometry corner, something you can physically bump into)", ["かど", "角"]),
            new("skilled / good at something / proficient", ["じょうず", "上手"]),

            new("each / at a time / gradually (incremental repetition or distribution)", ["ずつ"]),
            new("smooth/favorable/going well (idea: things are arranged properly or going in the right direction)", ["じゅんちょう", "順調"]),
            new("meeting/conference ('a gathering for discussion')", ["かいぎ", "会議"]),
            new("to move forward/advance / to make progress / time progresses / (sometimes) to proceed to the next stage", ["すすみます", "進みます"]),
            new("but/though/however (casual/neutral/straightforward, introduces a new sentence with contrast)", ["でも"]),
            new("but/though/however (casual/neutral soft speech-like connector, often after verbs/adjectives/nouns, not at start of sentence)", ["けど"]),
            new("but/though/however (casual/conversational, often used at start of sentence, and sometimes after verbs/adjectives/nouns)", ["だけど"]),
            new("but/though/however (formal/written/speeches, after period/semicolon/paragraph/break/comma)", ["しかし"]),
            new("to hold up/open (an umbrella) / sunlight shines/light enters / to pour (tea/alcohol into a cup, unusual)", ["さします", "差します"]),

            new("(I) will put up/open an umbrella.", ["傘を差します"]),
            new("Light is (in the state of) coming in through the window.", ["窓から光が差しています"]),
            new("The [meeting/conference] is progressing smoothly./The [meeting/conference] is going well.", ["会議が順調に進みます"]),
            new("The train is moving forward.", ["電車が進んでいます", "電車は進んでいます", "電車が進みます", "電車は進みます"]),
            new("The work is progressing./The work progresses.", ["仕事が進みます"]),
            new("Time is progressing./Time passes.", ["時間が進みます"]),
            new("The conversation is progressing./The story is progressing./The discussion progresses.", ["話が進みます"]),
            new("(I) move forward little by little./(We) make (forward) progress step by step.", ["少しずつ前に進みます"]),
            new("'one by one'", ["一つずつ"]),
            new("'10 minutes at a time’", ["十分ずつ"]),
            new("(I) eat (them) one by one.", ["一つずつ食べます"]),
            new("Please speak for 10 minutes each.", ["一人十分ずつ話してください"]),
            new("'little by little'", ["少しずつ"]),
            new("(I'm) (in the state of) preparing little by little.", ["少しずつ準備しています", "少しずつ準備をしています"]),
            new("(I'm) starting to understand Japanese little by little.", ["少しずつ日本語が分かってきました"]),
            new("Let's go (proceed/move forward) straight in that direction (over there). (polite, guiding) ('follow that direction (over there) straight ahead')", ["あちらをまっすぐ進みましょう", "あちらへまっすぐ進みましょう", "あちらの方へまっすぐ進みましょう"]),
            new("Next, go (proceed/move forward) straight along the narrow path.", ["次に、狭い道をまっすぐ進みます", "次に、まっすぐ狭い道を進みます"]),
            new("North is that way (over there in the distance) (make way explicit).", ["北はあちらです", "北はあちらの方です"]),
            new("(You) turn that way. ((you) turn toward that direction (over there).)", ["あちらに曲がります", "あちらを曲がります", "あちらへ曲がります", "あちらの方に曲がります", "あちらの方へ曲がります"]),
            new("(You) turn left at that corner (over there, it’s clearly the next/known corner).", ["あの角を左に曲がります", "あの角で左に曲がります"]),
            new("Please turn left at that corner (over there, it’s clearly the next/known corner).", ["あの角を左に曲がってください", "あの角で左に曲がってください"]),
            new("She is not (in the state of) holding up her umbrella.", ["彼女は傘を差していません"]),
            new("Aren't (you) cold?", ["寒くないですか", "寒くありませんか"]),
            new("I opened the large window, and let in the cool breeze/wind.", ["大きな窓を開けて、涼しい風を入れました", "大きな窓を開け、涼しい風を入れました", "大きい窓を開けて、涼しい風を入れました", "大きい窓を開け、涼しい風を入れました"]),
            new("When I opened the large window, cool air came in (toward me).", ["大きな窓を開けたら、涼しい風が入ってきました", "大きい窓を開けたら、涼しい風が入ってきました"]),
            new("It is a cold day today.", ["今日は寒い日です"]),
            new("Today is warm, and tomorrow is cool.", ["今日は暖かく、明日は涼しいです", "今日は暖かいけど、明日は涼しいです", "今日は暖かいですが、明日は涼しいです"]),
            new("It is cold at night.", ["夜は寒いです"]),
            new("It gets cold at night.", ["夜は寒くなります"]),
            new("It starts getting cold at night./It’s (now) beginning to get cold at night.", ["夜は寒くなってきます"]),
            new("It has started raining.", ["雨が降ってきました"]),

            new("is now / has become (and remains so) (present state)", ["なっています"]),
            new("had become / was (already) (past state) (no guarantee that state holds in present)", ["なっていました"]),
            new("will start to become / will gradually become (future change)", ["なってきます"]),
            new("has gradually become / has come to be (past → present change) (usually does still hold in the present)", ["なってきました"]),

            new("(I/They) have become good/are (now) good.", ["上手になっています"]),
            new("(By) last year (they) had become good.", ["去年は上手になっていました", "去年上手になっていました"]),

            new("From now on (I’ll) start getting better.", ["これから上手になってきます"]),
            new("From now on (I’ll) get even better.", ["これからもっと上手になってきます"]),
            new("(I’ve) been getting better", ["上手になってきました"]),
            new("I have gradually (little by little / bit by bit) been getting better.", ["少しずつ上手になってきました"]),

            new("It has started to get warm.", ["暖かくなってきました"]),
            new("Please hold up an umbrella.", ["傘を差してください"]),
            new("Can (I) hold up (my) umbrella?", ["傘を差してもいいですか"]),
            new("My room is over there. (female/neutral gender, polite and directional emphasis)", ["私の部屋はあちらです", "あちらが私の部屋です", "私の部屋はあちらにあります", "私の部屋があちらにあります"]),
            new("I forgot snacks.", ["お菓子を忘れました"]),
            ]),

        new("Section 4, unit 32 - Discuss relationships", [
            new("single (unmarried)", ["どくしん", "独身"]),
            new("to be born (polite form)", ["うまれます", "生まれます"]),
            new("divorce / to get divorced", ["りこん", "離婚"]),
            new("to pass away (to die) (polite, respectful, honorific)", ["なくなります", "亡くなります"]),
            new("to die (direct, neutral)", ["しにます", "死にます"]),
            new("young (Describing age, time/freshness)", ["わかい", "若い"]),
            new("'a large group of people'/crowd", ["おおぜい", "大勢"]),
            new("to call / to call out / to summon / to invite", ["よびます", "呼びます"]),
            new("boy", ["おとこのこ", "男の子"]),
            new("girl", ["おんなのこ", "女の子"]),
            new("all (of it) / the whole thing / everything (casual tone) (zoomed-in, practical “all of it”)", ["ぜんぶ", "全部"]),
            new("all / everything / the whole / entirely (formal / abstract tone) (zoomed-out, conceptual “everything”)", ["すべて", "全て"]),
            new("man/a male individual (direct / rough / casual)", ["おとこ", "男"]),
            new("woman/a female individual (direct / rough / casual)", ["おんな", "女"]),
            new("male/men (for formal, neutral, labels, signs, statistics, describing groups)", ["だんせい", "男性"]),
            new("female/women (for formal, neutral, labels, signs, statistics, describing groups)", ["じょせい", "女性"]),
            new("all members/everyone in a group", ["ぜんいん", "全員"]),
            new("person (polite form of 人)", ["かた", "方"]),
            new("who (polite version of 誰) (hiragana preferred)", ["どなた", "何方"]),


            new("(I) am a woman.", ["女です。"]),
            new("How many people is it/are there? (asking for number/count, not existence)", ["何人ですか"]),
            new("(I) have seven younger sisters.", ["妹が七人います"]),
            new("Who is this person here?/Who is this gentleman/lady? (polite)", ["こちらの方はどなたですか"]),
            new("Who is this person? (casual)", ["この人は誰ですか"]),
            new("See you / bye then, everybody.", ["じゃあね、皆", "じゃあね、皆さん"]),
            new("There are few people.", ["何人かいます", "人が少ないです", "人が少しいます", "少し人がいます", "少しの人がいます"]),
            new("(They) are all men. (formal+conversational) (all members (in the group) are men)", ["全員男性です", "全員男の人です"]),
            new("I will call her. (not explicitly by phone)", ["彼女を呼びます", "彼女を呼び出します"]),
            new("A large crowd came.", ["大勢が来ました"]),
            new("Let's get married.", ["結婚しましょう"]),
            new("Are (you) an adult?", ["大人ですか"]),
            new("He is an adult.", ["彼は大人です"]),
            new("Is she married?", ["彼女は結婚していますか"]),
            new("They got divorced. (male/neutral)", ["彼らは離婚しました"]),
            new("That dog died a hundred years ago.", ["その犬は100年前に死にました"]),
            new("A child was born./The baby was born./We had a child.", ["子供が生まれました", "赤ちゃんが生まれました"]),
            new("When were you born?", ["いつ生まれましたか", "お生まれはいつですか", "生まれはいつですか"]),
            new("She got divorced last year.", ["彼女は去年離婚しました", "去年彼女は離婚しました", "彼女は夫と去年離婚しました", "彼女は去年夫と離婚しました", "去年彼女は夫と離婚しました"]),
            new("Many people passed away (died) in 1600.", ["1600年に大勢の人が亡くなりました", "1600年に多くの人が亡くなりました", "1600年にたくさんの人が亡くなりました"]),
            new("There are a lot of men. (conversational, people-centered)", ["男の人がたくさんいます", "大勢の男の人がいます", "男の人が多いです", "多くの男の人がいます", "男の人が大勢います", "たくさんの男の人がいます"]),
            new("(I) am single.", ["独身です"]),
            new("'a single man' (formal)", ["独身の男性"]),
            new("I don't have a girlfriend.", ["彼女はいません", "彼女がいません"]),
            new("(I) went on a date with my boyfriend.", ["彼氏とデートしました", "彼氏とデートに行きました"]),
            new("I am still young. (male casual/polite speech)", ["僕はまだ若いです"]),
            new("Please call the teacher. (not explicitly by phone)", ["先生を呼んでください"]),
            new("My university friends are all still single.", ["大学の友達はまだ皆独身です", "大学の友達はまだ全員独身です", "まだ大学の友達は皆独身です", "まだ大学の友達は全員独身です"]),
            new("Tokyo has a lot of people./There are many people in Tokyo.", ["東京は人が多いです", "東京には人が多いです", "東京には人がたくさんいます", "東京に人がたくさんいます", "東京は人がたくさんいます", "東京には多くの人がいます", "東京に多くの人がいます"]),
            new("These girls are famous.", ["この女の子たちは有名です", "この女の子たちは皆有名です", "この女の子たちは全員有名です"]),
            new("How many people are in your family?", ["家族は何人いますか", "家族は何人ですか", "家族が何人いますか"]),
            new("There are four people in my family", ["家族は四人です", "家族が四人います", "家族は四人います", "四人家族です", "うちは四人家族です"]),
            new("(We) are a family of three. (My family is three people)", ["家族は三人です", "家族が三人います", "三人家族です", "家族は三人います", "うちは三人家族です"]),
            new("We are three people (in my family): my parents and me. (female/netural gender)", ["両親と私の三人です", "両親と私の三人家族です", "私と両親の三人です", "私と両親の三人家族です", "三人家族です"]),
        ]),

        new("Section 4, unit 31 - Shop for common items", [
            new("to hold / to carry / to have/possess / to keep/maintain (depending on context)", ["もちます", "持ちます"]),
            new("for (someone) / from the perspective of (someone)", ["にとって"]),
            new("take out / produce / bring out (core idea: moving something outward, not necessarily by pulling)", ["だします", "出します"]),
            new("important / precious / valuable", ["たいせつ", "大切"]),
            new("strong/sturdy/durable/healthy/robust (able to withstand stress, damage, or illness. Objects/People)", ["じょうぶ", "丈夫"]),
            new("this much / this degree / so (Used before adjectives or verbs, [how much/to what extent]-description)", ["こんなに"]),
            new("like this / such a / these kinds of", ["こんな"]),
            new("'except'/'other than'/'excluding' (in the outside-of-X domain) (structural exclusion)", ["いがいに", "以外に"]),
            new("'in other ways'/'in addition'/'besides (this)' (meaning: besides this/apart from this)", ["ほかに", "他に"]),
            new("'also besides that'/'even additionally' (there are already items being discussed, AND there are more beyond those)", ["ほかにも", "他にも"]),
            new("luggage / baggage / package / belongings / load", ["にもつ", "荷物"]),
            new("wristwatch", ["うでどけい", "腕時計"]),
            new("clock / watch / timepiece", ["とけい", "時計"]),

            new("There is money in the wallet. (existence+contrast) (As for in the wallet, money exists.)", ["財布にはお金があります。", "財布の中にはお金があります。", "財布にお金があります。", "財布の中にお金があります。"]),
            new("That (over there) is hers./That thing (over there) is hers.", ["あれは彼女の物です。", "あれは彼女のです。"]),
            new("Thanks for everything. (casual)", ["色々ありがとう。"]),
            new("I buy various items for trip preparation.", ["旅行の準備で色々な物を買います", "旅行の準備のために色々な物を買います", "旅行の準備として色々な物を買います"]),
            new("Who else is coming? (Besides (this), who comes?)", ["他に誰が来ますか。", "他に誰が来るの。", "他に誰が来るんですか。", "以外に誰が来ますか。", "以外に誰が来るの。", "以外に誰が来るんですか。"]),
            new("What else is there? (Besides (this), what exists?)", ["他に何がありますか。", "以外に何がありますか。"]),
            new("Is there anything else? (Besides (this), is there something that exists?)", ["他に何かありますか。"]),
            new("Who else is there? (Besides (this), who exists?)", ["他に誰がいますか。"]),
            new("What is there besides drinks?", ["飲み物の他に何がありますか。", "飲み物以外に何がありますか。"]),
            new("Are there other drinks?", ["他に飲み物がありますか", "他に飲み物はありますか。"]),
            new("There are all sorts of bags in this store.", ["この店には色々な鞄があります。", "この店には鞄が色々あります。", "この店に色々な鞄があります。", "この店に鞄が色々あります。", "この店は色々な鞄があります。", "この店は鞄が色々あります。"]),
            new("This is mine. (girl/gender neutral)", ["これは私の物です。", "これは私のです。"]),
            new("What else do you want?/What else do you like?", ["他に何が欲しいですか。", "他に何か欲しいですか。", "他に欲しい物はありますか。"]),
            new("We also have things like this./There are also items like these. (Also besides this, such things exist.)", ["他にもこんな物があります。", "他にもこんな物がございます。"]),
            new("(I) want all sorts of things.", ["色々欲しいです。", "色々な物が欲しいです。"]),
            new("This bag is durable.", ["この鞄は丈夫です。"]),
            new("(I) bought a sturdy wristwatch.", ["丈夫な腕時計を買いました。"]),
            new("Take good care of it./Cherish it./ Treat it carefully. (soft, friendly)", ["大切にして", "大切にしてください"]),
            new("(I) will put the wristwatch in the bag.", ["腕時計を鞄に入れます。", "鞄に腕時計を入れます。"]),
            new("I take a key out of a pocket.", ["ポケットから鍵を出します。", "鍵をポケットから出します。"]),
            new("I take money out of a wallet.", ["財布からお金を出します。", "お金を財布から出します。"]),
            new("This is something important for her. (As for this, it is important from her point of view.)", ["これは彼女にとって大切です", "彼女にとってこれは大切です"]),
            new("This is something important for me. (girl/neutral gender) (As for this, it is important from my point of view.)", ["これは私にとって大切です", "私にとってこれは大切です"]),
            new("This job is difficult for student. (work+/task)", ["この仕事は学生にとって難しいです。"]),

            new("I carry a bag.", ["鞄を持ちます", "鞄を持っています"]),
            new("I carry the luggage.", ["荷物を持ちます", "荷物を持っています"]),
            new("I carry an umbrella.", ["傘を持ちます", "傘を持っています"]),
            new("I have a car.", ["車を持っています"]),
            new("I have my passport.", ["パスポートを持っています"]),
            new("Do you have money (on/with you)?", ["お金を持っていますか"]),
            new("This battery lasts a long time.", ["この電池は長く持ちます", "この電池はあまり持ちます"]),
            new("This wall won't last long.",["この壁は長く持ちません"]),
            new("These shoes won't/dont last long.", ["この靴は長く持ちません", "この靴はあまり持ちません"]),
            new("Shall I help you? I’ll carry it.", ["手伝いましょうか。持ちます"]),
            new("The color is good.", ["色がいいです"]),
            new("Let's go to a different store. (“a different one (not this one)”)", ["違う店に行きましょう"]),
            new("(I) want a different bag. (“a different one (not this one)”)", ["違う鞄が欲しいです。"]),
            new("Do you have another color? (conversational/shopping)", ["他の色はありますか"]),
            new("Two of the same rice bowls please.", ["同じ茶碗を二つください"]),
            new("I want a wallet of the same color.", ["同じ色の財布が欲しいです"]),
            new("I want the same wallet as him.", ["彼と同じ財布が欲しいです", "彼のと同じ財布が欲しいです", ]),
            new("There is no other wristwatch as cute as this one.", ["こんなに可愛い腕時計は他にありません", "こんな可愛い腕時計は他にありません", "こんなに可愛い腕時計はありません", "こんな可愛い腕時計はありません"]),
            new("How about a bag like this?", ["こんな鞄はいかがですか", "こんな鞄はどうですか"]),
            new("May I carry the bag?", ["鞄を持ってもいいですか"]),
            ]),

        new("Section 4, unit 30 - Express days and times", [
            new("'counter for birds and winged animals'", ["わ", "羽"]),
            new("'every night'", ["まいばん", "毎晩"]),
            new("'every month'", ["まいつき", "毎月"]),
            new("congratulations", ["おめでとう"]),
            new("'The year before last'", ["おととし", "一昨年"]),
            new("'The year after next'", ["さらいねん", "再来年"]),

            new("It takes one day.", ["一日かかります。"]),
            new("It takes one year.", ["一年かかります。"]),
            new("It takes ten months.", ["十か月かかります。", "十ヶ月かかります。"]),
            new("It takes eleven months.", ["十一ヶ月かかります。", "十一か月かかります。"]),
            new("It takes twelwe months.", ["十二ヶ月かかります。", "十二か月かかります。"]),
            new("What year is next year?", ["来年は何年ですか。"]),
            new("What year was 'the year before last'?", ["一昨年は何年でしたか。"]),
            new("It took twenty days.", ["二十日かかりました。", "二十日間かかりました。"]),
            new("Last year was a good year.", ["去年はいい年でした。"]),
            new("Today is (my) birthday.", ["今日は誕生日です。"]),
            new("It takes one week.", ["一週間かかります。"]),
            new("It takes three weeks.", ["三週間かかります。"]),
            new("I drink milk every night.", ["毎晩牛乳を飲みます。", "毎晩は牛乳を飲みます。"]),
            new("(I) go to the hospital. (I’m heading out (from here) to the hospital.)", ["病院へ出掛けます。"]),
            new("I travel to the US every year. (Every year to Amerika for travel, (I) go)", ["毎年アメリカへ旅行に行きます。", "毎年アメリカへ旅行します。", "毎年アメリカに旅行に行きます。", "毎年アメリカに旅行します。", "毎年アメリカまで旅行に行きます。"]),
            ]),

        new("Section 4, unit 29 - Discuss food you like", [
            new("sour", ["すっぱい", "酸っぱい"]),
            new("'favorite food'/'favorite thing to eat'", ["こうぶつ", "好物"]),
            new("glass drinking glass / more stylish beverage glass", ["グラス"]),
            new("rice bowl", ["ちゃわん", "茶碗"]),
            new("bowl", ["ボウル"]),
            new("counter for long, cylindrical, stick-like objects (bottle, pen, umbrella, tree, banana, chopsticks)", ["本"]),
            new("glass (generic everyday cup / tumbler)", ["コップ"]),


            new("One fork please. (counter for long, cylindrical, stick-like objects)", ["フォークを一本ください"]),
            new("Two chopsticks please. (honorific, counter for long, cylindrical, stick-like objects)", ["お箸を二本ください"]),
            new("(I) am really sorry.", ["本当にすみません。"]),
            new("Half please./Please give me half./I’ll take half.", ["半分ください"]),
            new("(My) favorite food is sushi.", ["好物は寿司です。"]),
            new("These grapes are sour.", ["この葡萄は酸っぱいです。"]),
            new("Red wine please.", ["赤ワインをください", "赤ワインください"]),
            new("White wine please.", ["白ワインをください", "白ワインください"]),
            new("(We) make wine from grapes.", ["葡萄からワインを作ります"]),
            new("This soup is not very salty.", ["このスープはあまり塩っぱくないです。"]),
            new("(I) am really hungry.", ["本当にお腹が空きました"]),
            new("Let's wash the dishes.", ["お皿を洗いましょう。"]),
            new("(I) eat sushi with chopsticks. (honorific)", ["お箸で寿司を食べます。", "箸で寿司を食べます。"]),
            ]),

        new("Section 4, unit 28 - Get directions", [
            new("right beside / close to something (beside/adjacent/closely related) (“right around here/next to this thing”) (closer, narrower, more “next to” and less flexible than 近く)", ["そば"]),
            new("street (name)/“way things pass/flow”(often urban streets/named streets/emphasizes people/traffic passing through)", ["とおり", "通り"]),
            new("to pass through / to go through / to pass by", ["とおります", "通ります"]),
            new("Southwest", ["なんせい", "南西"]),
            new("Southeast", ["なんとう", "南東"]),
            new("Northwest", ["ほくせい", "北西"]),
            new("Northeast", ["ほくとう", "北東"]),
            new("North America", ["北アメリカ"]),
            new("South America", ["南アメリカ"]),
            new("over there / on the other side / beyond / the opposite side / the other party", ["むこう", "向こう"]),
            new("over there / that way / that person / that side (depends on ctx)　(polite あそこ)", ["あちら"]),
            new("there / that way / that side / you / your place (depends on ctx) (polite そこ)", ["そちら"]),
            new("which way / which direction / which one (polite)", ["どちら"]),


            new("Which way is the exit?/Where is the exit?/Which direction is the exit?", ["出口はどちらですか。"]),
            new("How do you get home?/How are you going home?/How do you return home?", ["どうやって家に帰りますか。", "家にどうやって帰りますか。", "どうやって家まで帰りますか。", "家までどうやって帰りますか。"]),
            new("Where is the hospital's entrance?", ["病院の入り口はどこですか。"]),
            new("I will go there./I’ll go that way./I’ll come to your place (polite form) (depends on ctx).", ["そちらに行きます。", "そちらへ行きます。"]),
            new("The road is over there (on the other side)", ["道は向こうです。", "道は向こうにあります。", ]),
            new("There is a station on the other side of the street/road. (On the road’s other side, there is a station.)", ["道の向こうに駅があります"]),
            new("First, you pass by a big hospital. (First, (you/I) pass through the vicinity of a big hospital (move along a route near it).)", ["まず、大きな病院のそばを通ります。", "まず、大きい病院のそばを通ります。", "初めに、大きな病院のそばを通ります。", "初めに、大きい病院のそばを通ります。"]),
            new("First, you pass by a small bank. (First, (you/I) pass through the vicinity of a small bank (move along a route near it).)", ["まず、小さな銀行のそばを通ります。", "まず、小さい銀行のそばを通ります。", "初めに、小さな銀行のそばを通ります。", "初めに、小さい銀行のそばを通ります。"]),
            new("(It's) a small hospital.", ["小さな病院です。", "小さい病院です。"]),
            new("Please open the store now. (As for the shop, please open it now.)", ["店を今開けてください", "今店を開けてください"]),
            //This path goes west. この道は西に行きます
        ]),

        new("Section 4, unit 27 - Talk about food and drink", [
            new("completely/entirely/at all/really (more emphatic/strong than 全然)", ["まったく"]),
            new("few/not many/not much/little/small amount (when the quantity or number of something is low)", ["すくない", "少ない"]),
            new("mint", ["ミント"]),
            new("dinner/evening meal (literal translation: evening meal)", ["ゆうはん", "夕飯"]),
            new("(your) mood/feeling (polite/formal)", ["ごきぶん", "ご気分"]),
            new("physical condition / health status", ["たいちょう", "体調"]),
            new("(your) opinion (polite/formal)", ["ごいけん", "ご意見"]),
            new("how / how about / how do you find it (evaluative/polite 'how about')", ["いかが", "如何"]),


            new("How is it? (evaluative/polite 'how about')", ["いかがですか。"]),
            new("What is your opinion? (polite/formal) (evaluative/polite 'how about')", ["ご意見はいかがですか。"]),
            new("How is your health? (evaluative/polite 'how about')", ["体調はいかがですか。"]),
            new("How are you feeling?/How is your mood? (evaluative/polite 'how about')", ["ご気分はいかがですか。"]),
            new("Doesn't it taste good?", ["美味しくないですか。"]),
            new("There's a lot of rice. (being served a meal. Most natural.)", ["ご飯が多いです。"]),
            new("There is not much soy sauce (in it/available). (being served a meal. Most natural.)", ["醤油が少ないです。"]),
            new("There is very little sugar.", ["砂糖がとても少ないです。"]),
            new("I like all of them./I like everything./I like them all.", ["全部好きです。"]),
            new("A drink please.", ["飲み物をください。", "飲み物ください。", "飲み物をお願いします。"]),
            new("No, I’m fine./No, thank you./No, that’s enough./No, I don’t need it. (No, that is fine/enough)", ["いいえ、結構です。"]),
            new("There's no food at all. (more emphatic/strong than 全然)", ["まったく食べ物がありません。", "まったく食べ物はありません。", "食べ物がまったくありません。", "食べ物はまったくありません。", "食べ物が全然ないです", "食べ物は全然ないです", "全然食べ物がないです", "全然食べ物はないです"]),
            new("It's very tasty. (formal/hospitality/service languages/written reviews)", ["たいへん美味しいです。", "大変美味しいです。"]),
            new("I drink black tea, and (then) I also drink coffee. (Drink black tea, and coffee also drink.)", ["紅茶を飲んで、コーヒーも飲みます。"]),
            new("I drink both black tea and coffee.", ["紅茶もコーヒーも飲みます。"]),
            new("Let's eat the lunchbox, and (then) go outside.", ["お弁当を食べて、外に行きましょう。", "弁当を食べて、外に行きましょう。"]),
            new("What would you like to drink? (honorific) (Your drink, what will you make it to/choose it as?)", ["お飲み物は何にしますか。"]),
            new("Would you like a boxed lunch? (honorific, evaluative/polite 'how about')", ["お弁当はいかがですか。", "弁当はいかがですか。"]),
            new("All (of them) please.", ["全部ください。", "全部をください。"]),
            new("All (of them) are tasty.", ["全部美味しいです。"]),
            ]),

        new("Section 4, unit 26 - Discuss weather", [
            new("daytime", ["ひるま", "昼間"]),
            new("This morning", ["けさ", "今朝"]),
            new("last night / the previous evening", ["ゆうべ", "夕べ"]),
            new("having become sunny / being clear (weather)", ["はれて", "晴れて"]),
            new("to fall (rain, snow, etc.)", ["ふります", "降ります"]),
            new("to blow (wind), to puff/play (instrument)", ["ふきます", "吹きます"]),

            new("How's the weather?", ["天気はどうですか。"]),
            new("It's not bad.", ["悪くないです。", "悪くはないです。"]),
            new("It's not (necessarily) bad. (slight nuance, soft hesitation), (As for bad, it is not.)", ["悪くはないです。"]),
            new("The weather is a little bad today. (As for today, the weather is a little bad.)", ["今日は天気が少し悪いです。", "今日は天気がちょっと悪いです。", "今日は天気があまりよくないです。", "今日は天気は少し悪いです。", "今日は天気はちょっと悪いです。", "今日は天気はあまりよくないです。", "今日天気が少し悪いです。", "今日天気がちょっと悪いです。", "今日天気があまりよくないです。", "今日天気は少し悪いです。", "今日天気はちょっと悪いです。", "今日天気はあまりよくないです。"]),
            new("The weather is not good this month. (As for this month, the weather is not good.)", ["今月は天気がよくないです。", "今月は天気はよくないです。", "今月天気がよくないです。", "今月天気はよくないです。"]),
            new("Today is a rainy day.", ["今日は雨の日です。"]),
            new("It rains. (Rain will fall/ rain falls.)", ["雨が降ります。"]),
            new("It snows. (Snow will fall/ snow falls.)", ["雪が降ります。"]),
            new("Snow is falling./It is snowing. (Snow is in the state of falling.)", ["雪が降っています。"]),
            new("It is not snowing, (It is snow that is not in the state of falling.)", ["雪が降っていません。"]),
            new("The sky is bright tonight. (As for tonight, the sky is bright.)", ["今晩は空が明るいです。", "今夜は空が明るいです。", "今晩は空は明るいです。", "今夜は空は明るいです。", "今晩空が明るいです。", "今夜空が明るいです。", "今晩空は明るいです。", "今夜空は明るいです。"]),
            new("Isn't it dark?", ["くらくないですか。", "暗くないですか。"]),
            new("The sky is clear. (The sky is in a state of having cleared up/become sunny.)", ["空が晴れています。", "空は晴れています。"]),
            new("The mirror is fogged upp/cloudy. (The mirror is in a fogged/clouded state.)", ["鏡が曇っています。", "鏡は曇っています。"]),
            new("The sky is cloudy. (The sky is in a clouded state.)", ["空が曇っています", "空は曇っています"]),
            new("The wind is blowing strongly. (The wind is in the state of blowing strongly.)", ["風が強く吹いています。", "風は強く吹いています。"]),
            new("The wind is weak.", ["風が弱いです。", "風は弱いです。"]),
            new("Today is sunny again. (As for today, it is again in a sunny state.)", ["今日はまた晴れています。", "今日また晴れています。"]),
            new("A weak wind is blowing. (Wind that is weak is in the state of blowing.)", ["弱い風が吹いています"]),
            new("Isn't the wind weak today? (use negation of adjective)", ["今日は風が弱くないですか。", "今日は風は弱くないですか。", "今日風が弱くないですか。", "今日風は弱くないですか。"]),
            new("Isn't the wind weak today? (use existence)", ["今日は風が弱くありませんか。", "今日は風は弱くありませんか。", "今日風が弱くありませんか。", "今日風は弱くありませんか。"]),
            new("How strong is the wind? (As for the wind, how strong is it?)", ["風はどれくらい強いですか。", "風はどれぐらい強いですか。", "風がどれくらい強いですか。", "風がどれぐらい強いですか。"]),
            new("What's tomorrows weather?", ["明日の天気はどうですか。", "明日はどんな天気ですか。", "明日の天気は何ですか。"]),
            new("It's neither good nor bad.", ["よくも悪くもないです。"]),
            new("Yesterday was cloudy. (As for yesterday, it was in a cloudy state.)", ["昨日は曇っていました"]),
        ]),

        new("Section 4, unit 25 - Describe your hobbies", [
            new("the week after next / in two weeks (from next week)", ["さらいしゅう", "再来週"]),
            new("I will teach/tell/inform", ["おしえます", "教えます"]),
            new("what (subject marker)", ["何が"]),
            new("something (unknown / unspecified) (used when offering help or proposing action)", ["何か"]),
            new("Well. / now then. / come on. / let’s see.", ["さあ"]),
            new("I will apply/put on/make/hang/spend", ["かけます", "掛けます"]),

            new("Let's stay at home.", ["家にいましょう。"]),
            new("Let's meet there.", ["あそこで会いましょう。", "そこで会いましょう。"]),
            new("I will meet up with a friend. (mutual action)", ["友達と会います。"]),
            new("I will meet my mother in the park.", ["公園で母に会います。"]),
            new("See you later.", ["またね。"]),
            new("See you next week.", ["また来週。"]),
            new("I will call the restaurant. (by phone)", ["レストランに電話を掛けます。", "レストランに電話します"]),
            new("(I) will call you (from) now. (Starting from now, I call to you (by phone).)", ["今からあなたに電話を掛けます", "今からあなたに電話します"]),
            new("Today I am not busy. (As for today, busy-ness does not exist.) (most polite form)", ["今日は忙しくありません。"]),
            new("Today I am not busy. (As for today, (it) is not busy.) (plain+polite form)", ["今日は忙しくないです。"]),
            new("I often cook.", ["よく料理します。"]),
            new("Shall (I) make something?", ["何か作りましょうか", "何かを作りましょうか"]),
            new("What do (you) like?", ["何が好きですか。"]),
            new("(My) teacher teaches both piano and guitar.", ["先生はピアノもギターも教えます。"]),
            new("in / for today's dish (specifically) (we) use eggs. (recall that dish is target of use)", ["今日の料理には卵を使います。"]),
            new("(We) use eggs in today’s dish. (recall that dish is target of use)", ["今日の料理に卵を使います。"]),
            new("I don't cook very often. (Cooking, as for it, I do not do (often).)", ["料理はあまりしません。"]),
            new("I walk (stroll) around the park. (I walk the park.)", ["公園を散歩します"]),
            new("I take a walk (stroll) in the park. (I take a walk at the park.)", ["公園で散歩します"]),
            new("Let's sit down and watch TV. (Sit down, and let’s watch TV.)", ["座ってテレビを見ましょう。"]),
            new("Let's do the laundry, and after that let's clean. (Do laundry, and then, let’s clean.)", ["洗濯して、それから掃除しましょう。", "洗濯して、その後掃除しましょう。"]),
            new("What food did you make?", ["何の料理を作りましたか。"]),
        ]),

        new("Section 4, unit 24 - Talk about clothes", [
            new("to wear (on the head)", ["かぶります", "被ります"]),
            new("pants", ["ズボン"]),
        ]),

        new("Section 4, unit 23 - Take public transit", [
            new("far/a distant place", ["とおく", "遠く"]),
            new("slow/late/delayed", ["おそい", "遅い"]),
            new("bicycle", ["じてんしゃ", "自転車"]),
            new("airport", ["くうこう", "空港"]),
            new("airplane", ["ひこうき", "飛行機"]),

            new("I stand on the train. (When I’m on the train, I (usually) stand. Apply contrast and habitual/future context)", ["電車では立ちます。"]),
            new("How long will it take?", ["どれぐらいかかりますか。", "どれくらいかかりますか。"]),
            new("It takes time (by nature).", ["時間がかかります。"]),
            new("I go far away/I go to a distant place. ((I) go to far.)", ["遠くに行きます。"]),
            new("It's neither fast nor slow. (It's not A either, not B either.)", ["速くも遅くもないです。"]),
            new("It's neither near nor far. (It's not A either, not B either.)", ["近くも遠くもないです。"]),
            new("The car in front (of me) is slow.", ["前の車は遅いです。"]),
            new("Is the train not here yet? (As for the train, is it still (not here)?)", ["電車はまだですか。"]),
            new("Isn't it fast?", ["速くないですか。"]),
            new("Isn't it dirty?", ["汚くないですか。"]),
        ]),

new("Section 4, unit 22 - Describe extended family", [
        new("grandfather / elderly man (someone else's)", ["おじいさん"]),
        new("grandmother / elderly woman (someone else's)", ["おばあさん"]),
        new("child (polite, another one's child(ren))", ["おこさん", "お子さん"]),
        new("To me/in my case (start of sentence)", ["私に"]),
        new("grandchild", ["まご", "孫"]),
        new("grandson", ["まごむすこ", "孫息子"]),
        new("granddaughter", ["まごむすめ", "孫娘"]),
        new("husband (someone else's, very polite)", ["ごしゅじん", "ご主人"]),
        new("husband (someone else's, medium polite, casual)", ["だんなさん", "旦那さん"]),
        new("husband (one's own)", ["おっと", "夫"]),
        new("husband (one's own, humble)", ["しゅじん", "主人"]),
        new("wife (someone else's, very polite)", ["おくさま", "奥様"]),
        new("wife (someone else's, medium polite, casual)", ["おくさん", "奥さん"]),
        new("wife (one's own)", ["つま", "妻"]),
        new("wife (one's own, most humble)", ["かない", "家内"]),
        new("relative", ["しんせき", "親戚"]),
        new("uncle", ["おじ"]),
        new("aunt", ["おば"]),

        new("mother ('a mother' as a role, not just 'my mother') (slightly more formal/descriptive than 母)", ["母おや", "母親"]),
        new("father ('a father' as a role, not just 'my dad') (slightly more formal/descriptive than 父)", ["父おや", "父親"]),


        new("Are you and she relatives?", ["あなたと彼女は親戚ですか。"]),
        new("This is my wife Erika.", ["こちらは妻のエリカです。", "こちらが妻のエリカです。"]),
        new("How old are you? (most polite, soft, respectful way)", ["おいくつですか。"]),
        new("[To me/in my case] (personally) have a wife and three children.", ["私には妻と三人の子供がいます。", "私には妻と子供が三人います。"]),
        new("I'm home./I'm back.", ["ただいま。",  "只今"]),
        new("Is your husband at home? (very polite)", ["ご主人はございたくですか。", "ご主人はご在宅ですか。", "旦那さんはご在宅ですか。"]),
        new("Take care./See you./Have a good day. (always from person staying)", ["行ってらっしゃい。"]),
        new("I'm leaving (and I'll come back)./I'm off. (always from person leaving)", ["行ってきます。"]),
        new("Welcome back.", ["おかえりなさい。"]),
        new("She does not resemble her father.", ["彼女は父親ににていません。", "彼女は父親に似ていません。", "彼女は父に似ていません。", "彼女はお父さんに似ていません。"]),
        new("Do you have grandchildren? (Are there grandchildren?) (honorific)", ["お孫さんがいますか。", "お孫さんはいますか。"]),
    ]),

    new("Section 4, unit 21 - Talk about hobbies", [
            new("counter for flat objects (paper, stamps, photos, plates, tickets, T-shirts)", ["まい", "枚"]),
            new("a walk / a stroll", ["さんぽ", "散歩"]),


            new("(I) did not write this book.", ["この本を書きませんでした。"]),
            new("(I) do not sing songs. (contrast on songs)", ["歌は歌いません。"]),
            new("(I) do [not very much/not often/to a small degree] go on walks.", ["散歩をあまりしません。", "あまり散歩しません。", "散歩はあまりしません。"]),
            new("(I) will draw a picture.", ["絵を描きます。"]),
            new("There are four photos.", ["写真が四枚あります。"]),
            new("Two slices of bread please.", ["パンを二枚ください。"]),
            new("What picture will you draw?", ["何の絵を描きますか。"]),
            new("(I) will take hundred photos.", ["写真を百枚撮ります。"]),
            new("(I) will write a letter to my friend.", ["友達に手紙を書きます。"]),
            ]),

    new("Section 4, unit 20 - Make requests", [
            new("right away, immediately", ["すぐに", "直ぐに"]),
            new("to stand up", ["たちます", "立ちます"]),
            new("to close (something - doors, windows, containers)", ["しめます", "閉めます"]),

            new("Are you busy on weekdays?", ["へいじつは忙しいですか。", "平日は忙しいですか。"]),
            new("Please do the laundry.", ["洗濯してください。"]),
            new("Please clean up.", ["掃除してください。"]),
            new("What are you doing here?", ["ここで何をしていますか。"]),
            new("What is he doing?", ["彼は何をしていますか。"]),
            new("And after that, I’ll clean. (very common, casual, polite, smooth tone)", ["それから、掃除します。", "それから、掃除をします。"]),
            new("They are cleaning.", ["彼らは掃除しています。"]),
            new("I went to school, and then studied. (use stem connection, and common+casual polite smooth tone. Optional to emphasize order)", ["学校に行き、それから勉強しました。", "学校に行き、勉強しました。"]),
            new("I will go right away. (polite)", ["すぐに行きます"]),
            new("Please read a lot of books.", ["本をたくさん読んでください。", "たくさん本を読んでください。"]),
            new("Please write.", ["書いてください。"]),
            new("Please listen.", ["聞いてください。"]),
            new("Please wait.", ["待ってください。"]),
            new("Please go home.", ["いえにかえってください。", "家に帰ってください。", "帰ってください。"]),
            new("Open the window. (non-polite, casual request / command among friends)", ["窓を開けて。"]),
            new("Please sit there.", ["そこに座ってください。"]),
            new("I am not writing. (I am not in the state of writing)", ["書いていません。"]),
            new("She is drinking water. (polite)", ["彼女は水を飲んでいます。"]),
            new("I will close the window.", ["窓をしめます。", "窓を閉めます。"]),
            new("Please close the window above the bookshelf. (mark window as thing being acted on)", ["本棚の上の窓をしめてください。", "本棚の上の窓を閉めてください。"]),
            new("Please stand up.", ["たってください。", "立ってください。"]),
            new("May I turn on the light?", ["でんきをつけていいですか。", "電気を付けていいですか。", "電気を付けてもいいですか。"]),
            new("Please turn on the light.", ["でんきをつけてください。", "電気を付けてください。"]),
            new("I stood up immediately, and turned on the lights. (Immediately stood (te-form to connect verbs), (and) turned on the light.) (make it less explicit between connection)", ["すぐに立って、電気を付けました。", "すぐに立って電気を付けました。"]),
            new("Please close the window and turn on the light. (smooth, flow, polite and compact. Use te-form to connect)", ["窓を閉めて電気を付けてください。", "窓を閉めて、電気を付けてください。"]),
            new("Please do the laundry immediately.", ["すぐに洗濯してください。"]),
            new("Please clean the house.", ["家の掃除をしてください。"]),
            new("(I/he/she) [did not stand up/didn't stand]. (polite)", ["立ちませんでした。"]),
            new("Sorry for drinking your coffee. ('your' is explicit)", ["あなたのコーヒーを飲んですみません。"]),
        ]),

    new("Section 4, unit 19 - Say where things are", [
            new("small, tucked-away area in a corner (literal or figurative)", ["かたすみ", "片隅"]),
            new("corner / nook / corner area (not sharp — more like a zone or area) (indoors/outdoors/abstract spaces that is away from the center)", ["すみ", "隅"]),
            new("counter for books, notebooks, magazines, albums, booklets", ["さつ", "冊"]),

            new("There are chairs to the left and right of the table. (location first)", ["テーブルの左と右に椅子があります。"]),
            new("It's on the bottom left. (short, point out existence for a thing)", ["左下にあります。"]),
            new("There is a chair [beside/at the side of] the table. (location first)", ["テーブルのよこに椅子があります。", "テーブルの横に椅子があります。"]),
            new("I am in front of you. (concise, location first)", ["あなたの前にいます。"]),
            new("There's a table in front of me. (concise, location first)", ["前にテーブルがあります。"]),
            new("I have ten books. / There are ten books.", ["本が十さつあります。", "本が十冊あります。"]),
            new("There are four books on the bookshelf. (introduce books first, not the shelf)", ["本が本だなに四さつあります。", "本が本棚の上に四冊あります。"]),
            new("The mirror is in the corner (literal/figurative). (introduce mirror first)", ["かがみはかたすみにあります。", "鏡は片隅にあります。", "鏡が片隅にあります。"]),
            new("My older sister is outside. (concise, location first)", ["外に姉がいます。"]),
            new("My older brother is inside. (concise, location first)", ["中に兄がいます。"]),
            new("I am busy for a little while. (For a short interval, I am busy.)", ["ちょっとの間忙しいです。"]),
            new("This is a souvenir from the United States.", ["これはアメリカからのお土産です。"]),
            new("The chair is under that.　(simple, chair as topic, very common in conversation)", ["椅子はその下です。"]),
        ]),

    new("Section 4, unit 18 - Talk about your schedule", [
            new("the day after tomorrow", ["あさって", "明後日"]),

            new("I work on Saturdays. (in general, usually part of job)", ["土曜日に働きます。", "土曜日は働きます。"]),
            new("I come here often. (emphasize 'as for here, I come often')", ["ここにはよく来ます。", "よくここには来ます。"]),
            new("How's today? (imply asking about someone’s day or situation)", ["今日はどうですか。"]),
            new("They will talk. (male/mixed group)", ["彼らは話します。"]),
            new("I speak English.", ["英語を話します。"]),
            new("I don't talk to her. (implying contrast or emphasis)", ["彼女とは話しません。"]),
            new("What's your work? (shortest form but polite)", ["おしごとは。", "お仕事は。"]),
            new("How many hours do they work?　(Make male/mixed group explicit. In general, usually part of job)", ["かれらは何時間はたらきますか。", "彼らは何時間働きますか。"]),
            new("I did not buy that book.", ["その本を買いませんでした。"]),
        ]),

    new("Section 4, unit 17 - Ask about food", [
            new("It's time for breakfast.", ["朝ご飯の時間です。"]),
            new("I don't like fish. (stronger negative, stating fact - dislike/hate)", ["魚が嫌いです。"]),
            new("What kinds of rice balls do you have? (polite, soft, conversational, natural in shops)", ["どんなおにぎりがあるんですか。"]),
        ]),

    new("Section 4, unit 16 - Talk about your family", [
            new("Those people/they (common in speech)", ["あの人たち"]),
            new("They (female group)", ["かのじょたち", "彼女たち"]),
            new("They (male/mixed group)", ["かれら", "彼ら"]),

            new("Who are you / Who is it (implies 'Who is this person?')", ["だれですか。","誰ですか。"]),
            new("Excuse me, who are you?", ["すみません、あなたはだれですか。", "すみません、あなたは誰ですか。"]),
            new("Who is he?", ["かれはだれですか。", "彼は誰ですか。"]),
            new("Who is she?", ["かのじょはだれですか。", "彼女は誰ですか。"]),
            new("Who is that?　(make 'that' explicit. Usually implies a person)", ["あれはだれですか。", "あれは誰ですか。"]),
            new("Who is that person?", ["あの人はだれですか。", "あの人は誰ですか。"]),
            new("They are students. (male/mixed group)", ["かれらは学生です。", "彼らは学生です。"]),
            new("Whose computer is this?", ["これは誰のパソコンですか。", "このパソコンは誰のですか。"]),
            new("She is my older sister. (girl/neutral gender)", ["かのじょは私のあねです。", "彼女は私の姉です。"]),
            new("Are they sisters? (female group)", ["かのじょたちはしまいですか。", "彼女たちは姉妹ですか。"]),
            new("We are sisters.", ["私たちはしまいです。", "私たちは姉妹です。"]),
            new("I am his younger brother. (male casual/polite speech)", ["ぼくはかれの弟です。", "僕は彼の弟です。"]),
            new("Are they/you siblings? (short, concise)", ["きょうだいですか。", "兄弟ですか。"]),
            new("My/our family is big.", ["うちの家族は大きいです。"]),
            new("Is this yours?", ["これはあなたのですか。"]),
            new("Do you have siblings?", ["きょうだいはいますか。", "兄弟はいますか。"]),
            new("My older brother is allergic to milk.", ["兄は牛乳にアレルギーがあります。", "兄は牛乳アレルギーがあります", "兄は牛乳アレルギーです"]),
            new("No, I don't have a family.", ["いいえ、家族はいません。"]),
            new("My older brother's name is Kenta. (short, concise)", ["兄の名前は健太です。"]),
            new("Who is his younger brother?", ["かれの弟はだれですか。", "彼の弟は誰ですか。"]),
        ]),

    new("Section 4, unit 15 - Talk about yourself", [
            new("My name is Tanaka. (very polite (humble), business/formal intros)", ["田中と申します。"]),
            new("That’s wrong/not correct/different", ["ちがいます", "違います"]),
            new("What's the difference?", ["ちがいは何ですか。", "違いは何ですか。"]),
            new("Are you a foreigner?", ["がいこく人ですか。", "外国人ですか。"]),
            new("Are you a foreign exchange student?", ["りゅうがくせいですか。", "留学生ですか。"]),
            new("I will eat two eggs. (use counter for small, round/compact objects.)", ["卵を二こ食べます。", "卵を二個食べます。"]),
            new("What grade are you in?", ["何年生ですか。"]),
        ]),
    new("Section 4, unit 14 - Describe your home", [
            new("I'm at school.", ["学校にいます。"]),
            new("There are puppies and kittens.", ["こいぬとこねこがいます。", "子犬と子猫がいます。"]),
            new("There are three windows in the room. (emphasize room with contrast, use existence)", ["部屋には窓が三つあります。"]),
        ]),

    new("Section 4, unit 13 - Talk about your day", [
            new("bedroom (formal, non-English everyday speech)", ["しんしつ", "寝室"]),
            new("kitchen (traditional/general)", ["だいどころ", "台所"]),
            new("midnight (zero o’clock) (12:00 AM / midnight / 00:00)", ["れいじ", "零時", "午前零時"]),


            new("Welcome to Japan.", ["ようこそ日本へ。", "日本へようこそ"]),
            new("I go to sleep at midnight. (formal, 'a.m. 00:00')", ["ごぜんれいじに寝ます。", "午前零時に寝ます。", "零時に寝ます。"]),
            new("I go to sleep at midnight. ('in the middle of the night')", ["まよなかに寝ます。", "真夜中に寝ます。"]),
            new("The school is in Japan.", ["学校は日本にあります。"]),
            new("I get up around six o'clock.", ["六時ごろに起きます。", "六時ごろ起きます。"]),
            new("Where is a big department store?　(existence)", ["大きいデパートはどこにありますか。", "大きなデパートはどこにありますか"]),
            new("Is there a big department store?", ["大きいデパートはありますか。", "大きなデパートはありますか。"]),
            new("I will not go to the company.", ["会社に行きません。"]),
            new("Are there two? (things, focus on existence or quantity)", ["二つありますか。"]),
            new("Are there two? (things, less about existence, more about identifying/confirming)", ["二つですか。"]),
            new("There are four tables.", ["テーブルが四つあります。"]),
            new("I have time. (I, on the other hand, have time.)", ["私には時間があります。"]),
            new("I have time. (compact and natural.)", ["時間があります。"]),
            new("There is no bathtub.", ["お風呂はありません。"]),
            new("It is over here. (emphasize existence in a location)", ["ここにあります", "こちらにあります"]),
            new("It is over here. (neutral for people/things)", ["ここです。", "こちらです"]),

            new("Which park should we go to?", ["どの公園に行きましょうか。"]),
            new("I go shopping.", ["買い物に行きます。"]),
        ]),

    new("Section 4, unit 12 - Discuss a meal", [
            new("What's (your) name? (honorific/politeness prefix)", ["お名前は何ですか。"]),
            new("Which one is it?", ["どれですか。"]),
            new("Which one is the water? (Which one is the one that is water?)", ["どれが水ですか。"]),
            new("Which one will you drink?", ["どれを飲みますか。"]),
            new("I eat a lot.", ["たくさん食べます。"]),
            new("Thank you for the meal (phrase said after finishing a meal)", ["ごちそうさまでした。"]),
            new("It's exactly ten thirty.", ["十時半ちょうどです。", "ちょうど十時半です。"]),
            new("It's exactly ten thirty right now.", ["今ちょうど十時半です。","今十時半ちょうどです。", "今はちょうど十時半です。", "今は十時半ちょうどです。"]),
            new("Well then, let's go to Shibuya.", ["では、渋谷に行きましょう。", "じゃあ、渋谷に行きましょう。"]),
            new("I eat at around ten o'clock.", ["十時ごろに食べます。", "十時ごろ食べます。", "十時ぐらいに食べます。", "十時ぐらい食べます。", "十時くらいに食べます。", "十時くらい食べます。"]),
        ]),

    new("Section 4, unit 11 - Communicate at a store", [
            new("meat bun", ["肉まん"]),
            new("to warm/heat", ["あたためます", "温めます"]),
            new("to push/press (for buttons, doors, or stamps/seals)", ["おします", "押します"]),
            new("instant cup noodles / cup ramen", ["カップラーメン"]),
            new("to pull out/take out/withdraw from inside something (literally/figuratively, money or eliciting something. Core idea: Pull something outward/from inside)", ["ひきだします", "引き出します"]),
            new("fermented soybeans", ["なっとう", "納豆"]),
            new("copy machine", ["コピーき", "コピー機"]),


            new("You can do it at that store over there.", ["あの店で出来ます。"]),
            new("I will copy the notebook.", ["ノートをコピーします。"]),
            new("It's open 24 hours", ["二十四時間あいています。", "二十四時間開いています。"]),
            new("It's open until ten.", ["十時まであいています。", "十時まで開いています。"]),
            new("That convenience store over there is open now.", ["あのコンビニは今あいています。", "あのコンビニは今開いています。"]),
            new("Open 24 hours / open 24 hours a day. (common for shops)", ["二十四時間えいぎょうしています。", "二十四時間営業しています。"]),
            new("I want to buy a few drinks.", ["飲み物をいくつか買いたいです。"]),
            new("Got it / understood.", ["分かりました。"]),
            new("This way. (describe as movement / direction, or as explanation / pointing out location)", ["こちらへ", "こちらです"]),
            new("Can you scan it?", ["スキャン出来ますか。"]),
            new("Please wait a moment.　(with politeness prefix)", ["しょうしょうおまちください。", "少々お待ちください。"]),
            new("Can I also scan textbooks at the convenience store?", ["コンビニできょうかしょのスキャンも出来ますか。", "コンビニで教科書のスキャンも出来ますか。"]),
            new("I want to buy postage stamps.", ["きってが買いたいです。", "切手が買いたいです。", "切手を買いたいです。"]),
            new("I need a bit of money later.", ["後で少しお金が要ります。", "後でお金が少し要ります。"]),
            new("How much are you going to withdraw?", ["いくらひきだしますか。", "いくら引き出しますか。"]),
            new("I want to withdraw money.", ["お金をひきだしたいです。", "お金を引き出したいです。"]),
            new("It comes to 100 yen./it will be 100 yen.", ["百円になります。"]),
            new("Altogether it's 100 yen. (Altogether it comes to 100 yen.)", ["全部で百円になります", "全部百円になります"]),
            new("I already (postage) stamped it.", ["もうきってをおしました。", "もう切手を押しました。"]),
            new("Should I warm up the beef bowl?", ["ぎゅうどんをあたためましょうか。", "牛丼を温めましょうか。"]),
            new("You press this button.", ["このボタンをおします。", "このボタンを押します。"]),
            new("Lemon chewing gum", ["レモンのガム"]),
            new("Here you go.", ["どうぞ。"]),
            new("I'm going to pay with my smartphone.", ["スマホではらいます。", "スマホで払います。"]),
            new("I want to pay with a credit card.", ["クレジットカードではらいたいです。", "クレジットカードで払いたいです。"]),
            new("Here you go, your change.", ["どうぞ、おつりです。", "どうぞ、お釣りです。"]),
            new("Here you go, your meat bun.", ["どうぞ、肉まんです。", ]),
            new("I don't need a straw. (customer service situation, Polite and softer than 要りません)", ["ストローはだいじょうぶです。", "ストローは大丈夫です。"]),
            new("Do you have money now? (Do you have money on you?)", ["今お金をもっていますか。", "今お金を持っていますか。"]),
            new("A lot of money.", ["たくさんのお金。"]),
        ]),

        new("Section 4, unit 10 - Buy stationery", [
            new("which day", ["なんにち", "何日"]),
            new("which day of the week", ["何曜日"]),
            new("calendar", ["カレンダー"]),
            new("sticky notes", ["ふせん", "付箋"]),
            new("stapler", ["ホチキス"]),
            new("scissor", ["はさみ", "ハサミ"]),
            new("to prepare/to get ready/to make preparations (します)", ["準備をします", "準備します"]),
            new("stationery / writing supplies / office supplies", ["ぶんぼうぐ", "文房具"]),


            new("I'm going to prepare for school", ["学校のじゅんびをします。", "学校の準備をします。"]),
            new("I am ready / preparations are done.", ["じゅんびが出来ました。", "準備が出来ました。"]),
            new("School begins (from) next week.", ["学校は来週から始まります。", "学校は来週始まります。", "来週から学校が始まります。", "来週学校が始まります。"]),
            new("On which day are you going to school?", ["何日に学校に行きますか。", "学校には何日に行きますか。", "学校に何日に行きますか。"]),
            new("By the way, when is school?", ["ところで、学校はいつですか。"]),
            new("Do you need an eraser?", ["けしゴムはいりますか。", "消しゴムは要りますか。"]),
            new("I need coloured pencils.", ["色えんぴつがいります。", "色鉛筆が要ります。"]),
            new("This mechanical pencil is cute and cheap.", ["このシャーペンは可愛くて安いです。"]),
            new("Stylish design.", ["お洒落なデザイン。"]),
            new("Those scissors are lightweight and cheap.", ["そのハサミはかるくて安いです。", "そのハサミは軽くて安いです。"]),
            new("It's an expensive and pretty notebook.", ["高くて綺麗なノートです。"]),
            new("This scissor is cheap and pretty.", ["このハサミは安くて綺麗です。"]),
            new("This stapler is expensive, but cool.", ["このホチキスは高いけど、かっこいいです。"]),
            new("thick notebook", ["あついノート", "厚いノート"]),
            new("I'll probably go with that stapler.", ["多分そのホチキスにします。"]),
            new("I want a cheap and cute calendar.", ["安くて可愛いカレンダーが欲しいです。"]),
            new("It's a hundred yen off　(it's 100 yen discount)", ["百円びきです。", "百円引きです。"]),
            new("These sticky notes are half price.", ["このふせんははんがくです。", "この付箋は半額です。"]),
            new("Which store's colored pencils are good?", ["どの店の色鉛筆がいいですか。"]),
            new("Because this store's sticky notes are cheap and good, I will buy a lot.", ["この店のふせんは安くていいので、たくさん買います。", "この店の付箋は安くていいので、たくさん買います。"]),
            new("I will write this year’s schedule on this calendar.", ["このカレンダーに今年のスケジュールを書きます。"]),
            ]
        ),

        new("Section 4, unit 9 - Desribe a recent date",[
            new("pudding", ["プリン"]),
            new("fishing", ["つり", "釣り"]),
            new("license / permit / certification", ["めんきょ", "免許"]),

            new("We text everyday.", ["毎日メールします。"]),
            new("Kai can drive.", ["かいさんは運転が出来ます。"]),
            new("Can Ken play golf?", ["けんさんはゴルフが出来ますか。"]),
            new("Ken has has a red car.", ["けんさんは赤い車を持っています。"]),
            new("Erika is good at table tennis.", ["エリカさんはたっきゅうがとくいです。", "エリカさんは卓球が得意です。"]),
            new("Sam's hobby is table tennis.", ["サムさんの趣味は卓球です。"]),
            new("The next date is on the twentieth.", ["つぎのデートははつかです。", "次のデートは二十日です。"]),
            new("July the twentieth is good.", ["七月はつかがいいです。", "七月二十日がいいです。"]),
            new("We're going to Shibuya to eat lunch.", ["渋谷に昼ご飯を食べに行きます。"]),
            new("Hana uses a lot of spices.", ["花さんはスパイスをたくさん使います。"]),
            new("This wednesday. Next wednesday.", ["今週の水曜日。来週の水曜日。"]),
            new("I have a lot of sports equipment. (ownership)", ["スポーツようひんをたくさんもっています。", "スポーツ用品をたくさん持っています。", "たくさんのスポーツ用品を持っています。", "スポーツ用品はたくさん持っています。"]),
            ]),

        new("Section 4, unit 8 - Talk about classes at university",[
            new("to choose / to select / to pick", ["えらびます", "選びます"]),
            new("by all means/definitely/certainly/please do (strongly encourage/express desire)", ["ぜひ", "是非"]),
            new("theater / drama / stage play", ["えんげき", "演劇"]),
            new("international student", ["りゅうがくせい", "留学生"]),
            new("Europe", ["ヨーロッパ"]),
            new("media center/library/resource center", ["メディアセンター"]),
            new("programming language", ["プログラミングげんご", "プログラミング言語"]),
            new("textbook", ["きょうかしょ", "教科書"]),
            new("economics", ["けいざいがく", "経済学"]),
            new("biology", ["せいぶつがく", "生物学"]),
            new("to finish, to end, to be over", ["おわります", "終わります"]),
            new("this semester / the current school term", ["こんがっき", "今学期"]),
            new("next semester / the next school term", ["らいがっき", "来学期"]),
            new("to receive / to take (exam/lesson/test) / to accept", ["うけます", "受けます"]),

            new("Professor Tanaka is on campus once a week. (casual count)", ["田中先生は週に一回キャンパスにいます。", "週に一回田中先生はキャンパスにいます。", "田中先生はキャンパスに週に一回います。"]),
            new("How many history students are there?", ["歴史の学生は何人いますか。"]),
            new("There are 11 literature students.", ["ぶんがくのがくせい[が/が]十一人います。", "文学の学生が十一人います。", "文学の学生は十一人います。"]),
            new("Are you finished with the history assignment?", ["れきしのかだいはおわりましたか。", "歴史の課題は終わりましたか。"]),
            new("The teacher is strict, but nice.", ["先生は厳しいけど、優しいです。"]),
            new("Office hours are from 10 o'clock on Thursday.", ["オフィスアワーは木曜日の十時からです。"]),
            new("I have a business class twice a week. (casual, straightforward count)", ["週に二回ビジネスのじゅぎょうがあります。", "週に二回ビジネスの授業があります。"]),
            new("We're doing biology homework as a group.", ["グループでせいぶつがくのしゅくだいをします。", "グループで生物学の宿題をします。"]),
            new("We often practice Spanish as a group", ["グループでよくスペイン語を練習します", "よくグループでスペイン語を練習します", "グループでスペイン語をよく練習します"]),
            new("I occasionally practice Japanese with my classmate.", ["たまにクラスメイトと日本語を練習します。", "クラスメイトとたまに日本語を練習します。"]),
            new("The economics assignments are difficult, but classes are fun.", ["けいざいがくのかだいはむずかしいけど、じゅぎょうはたのしいです。", "経済学の課題は難しいけど、授業は楽しいです", "経済学の課題は難しいけど、授業が楽しいです"]),
            new("economics textbook (published, printed, sold book)", ["けいざいがくのきょうかしょ", "経済学の教科書"]),
            new("Inside the media center is quiet and comfortable/cozy.", ["メディアセンターの中はしずかでかいてきです。", "メディアセンターの中は静かで快適です。"]),
            new("How's next month's schedule?", ["来月のスケジュールはどうですか。"]),
            new("What are you going to study next semester?", ["らいがっき何をべんきょうしますか。", "来学期何を勉強しますか。"]),
            new("Which classes did you choose?", ["どのじゅぎょうをえらびましたか。", "どの授業を選びましたか。"]),
            new("We should definitely do assignments together next time.", ["こんどぜひ一緒にかだいをしましょう。", "今度是非一緒に課題をしましょう。"]),
            new("I don't want to do the programming homework.", ["プログラミングのしゅくだいはしたくないです。", "プログラミングの宿題はしたくないです。", "プログラミングの宿題をしたくないです。"]),
            new("I want to study abroad in Germany.", ["ドイツにりゅうがくしたいです。","ドイツに留学したいです。"]),
            ]),

        new("Section 4, unit 7 - Connect two adjectives",[
            new("amazing / incredible / wow / awesome", ["すごい", "凄い"]),
            new("the best / supreme / awesome / top-notch", ["さいこう", "最高"]),
            new("cook (head chef / someone skilled in cooking)", ["シェフ"]),
            new("healthy", ["ヘルシー"]),
            new("apartment building / condominium", ["マンション"]),
            new("rooftop", ["おくじょう", "屋上"]),
            new("website", ["サイト"]),
            new("to look up / investigate / check / examine", ["しらべます", "調べます"]),

            new("I will look up the menu.", ["メニューをしらべます。", "メニューを調べます。"]),
            new("That restaurant (over there) is on the third floor. (emphasize location)", ["あのレストランは三階にあります。"]),
            new("Which floor is the restaurant on? (emphasize location)", ["レストランは何階にありますか。"]),
            new("This pizza shop is lovely and famous.", ["このピザ屋は素敵で有名です。"]),
            new("The staff here is always the best.", ["ここのスタッフはいつもさいこうです。", "ここのスタッフはいつも最高です。"]),
            new("It gets crowded on Fridays.", ["金曜日はこみます。", "金曜日は混みます。", "金曜日は込みます。"]),
            new("Around what time does it get crowded?", ["何時ごろこみますか。", "何時ごろ混みますか。", "何時ごろ込みますか。"]),
            new("Does it get crowded around twelve?", ["十二時ごろはこみますか。", "十二時ごろは混みますか。", "十二時ごろは込みますか。", "十二時ごろ混みますか。", "十二時ごろ込みますか。"]),
            new("I'll check on a website.", ["サイトでチェックします。"]),
            new("That's so, isn't it? / Let me see / Hmm, yes / right",["そうですね。"] ),
            new("The cucumber salad there is famous.", ["そこの胡瓜サラダは有名です。"]),
            new("Let's go with that stylish vegetarian restaurant.", ["そのお洒落なベジタリアンレストランにしましょう。"]),
            new("I'm going to make a reservation for 8 o'clock.", ["八時の予約を入れます。"]),
            new("What time should we make a reservation for?", ["何時の予約を入れましょうか。"]),
            new("Right, it's cheap so let's eat at this sushi restaurant.", ["そうですね、安いのでこの寿司屋で食べましょう。"]),
            ]),

        new("Section 4, unit 6 - Make plans to go out",[
            new("actress", ["じょゆう", "女優"]),
            new("genre", ["ジャンル"]),
            new("arcade / game center", ["ゲームセンター"]),
            new("parfait (dessert, layers of ice cream, fruit, syrup, whipped cream)", ["パフェ"]),
            new("bowling", ["ボウリング"]),
            new("earring", ["イヤリング"]),
            new("shopping mall", ["ショッピングモール"]),
            new("tower", ["タワー"]),
            new("Japanese-style pub / bar / casual drinking restaurant", ["いざかや", "居酒屋"]),

            new("The ending of the movie was sad. (focus on identifying what was sad)", ["えいがのけつまつがかなしかったです。", "映画の結末が悲しかったです。"]),
            new("Would you like to go see a comedy movie?", ["コメディえいがをみに行きませんか。", "コメディ映画を見に行きませんか。"]),
            new("Would you like to go eat a parfait?", ["パフェを食べに行きませんか。"]),
            new("After the movie, would you like to go drink?", ["映画の後、飲みに行きませんか。"]),
            new("Let's go eat caramel somewhere.", ["どこかにキャラメルを食べに行きましょう。"]),
            new("Would you like to go to Ueno to buy books?", ["上野に本を買いに行きませんか。"]),
            new("After that, let's go to Shinjuku to hang out together.", ["その後、いっしょにしんじゅくにあそびに行きましょう。", "その後、一緒に新宿に遊びに行きましょう。"]),
            new("Yes, sounds good. (seeking agreement or confirmation)", ["はい、いいですね。"]),
            new("That also sounds good. (seeking agreement or confirmation)", ["それもいいですね。"]),
            new("No, it's not good at all.", ["いいえ、ぜんぜんよくないです。", "いいえ、全然よくないです。"]),
            new("There's a nice movie theater south of the station.", ["駅の南にいい映画館があります。"]),
            new("The movie theater south of the department store is cheap.", ["デパートの南の映画館は安いです。"]),
            new("Tokyo’s night view is pretty.", ["東京の夜のけしきはきれいです。", "東京の夜の景色は綺麗です。"]),

            ]
        ),

        new("Section 4, unit 5 - Describe a wedding",[
            new("I rented a limousine with my family.", ["かぞくとリムジンをかりました。", "家族とリムジンを借りました。"]),
            new("The venue wasn't big.", ["かいじょうは大きくなかったです。", "会場は大きくなかったです。"]),
            new("The venue wasn't close.", ["かいじょうは近くなかったです。", "会場は近くなかったです。"]),
            new("The wedding decorations weren't pretty.", ["けっこんしきのデコレーションはきれいじゃなかったです。", "結婚式のデコレーションは綺麗じゃなかったです。"]),
            new("The bride's dress was elegant.", ["しんぷのドレスうつくしかったです。", "新婦のドレスは美しかったです。"]),
            new("The guests were not lively.", ["ゲストはにぎやかじゃなかったです。", "ゲストは賑やかじゃなかったです。"]),
            new("I greeted Ken's father.", ["けんさんのお父さんにあいさつしました。", "けんさんのお父さんに挨拶しました。"]),
            new("The groom's relatives weren't nice.", ["しんろうのしんせきはやさしくなかったです。", "新郎の親戚は優しくなかったです。"]),
            new("The carpet/rug's color was hideous.", ["カーペットの色はダサかったです。"]),
            new("The cake's flavor was very weird.", ["ケーキのあじはとてもへんでした。", "ケーキの味はとても変でした。"]),
            new("The tables were low.", ["テーブルはひくかったです。", "テーブルは低かったです。"]),
            new("The jazz band's performance was terrible.", ["ジャズバンドのパフォーマンスはひどかったです。", "ジャズバンドのパフォーマンスは酷かったです。"]),
            new("The singer's song was terrible.", ["かしゅのうたはひどかったです。", "歌手の歌は酷かったです。"]),
            new("Because the limousine was expensive, we took a bus.", ["リムジンは高かったので、バスに乗りました。"]),
            new("After the meal, there was a boring speech.", ["ご飯の後、詰まらないスピーチがありました。"]),
            new("The day before yesterday I did nothing all day.", ["おとといいちにちじゅう何もしませんでした。", "一昨日一日中何もしませんでした。", "一昨日は一日中何もしませんでした。"]),
            new("I went to the wedding by limo with some other people.", ["ほかの人とリムジンでけっこんしきに行きました。", "他の人とリムジンで結婚式に行きました。"]),
            ]
        ),

        new("Section 4, unit 4 - Discuss what to eat",[
            new("family restaurant (casual chain restaurant)", ["ファミレス"]),
            new("drink bar / self-service beverage station", ["ドリンクバー"]),
            new("broccoli", ["ブロッコリー"]),
            new("expression said before meals / I humbly receive (this food) / let's eat", ["いただきます", "頂きます"]),
            new("mayonnaise", ["マヨネーズ"]),
            new("half / halfway. Commonly used for dividing things or amounts, as well as time or distance", ["はんぶん", "半分"]),


            new("Which do you prefer, seafood or meat? / Seafood or meat, which is better?", ["シーフードと肉、どちらがいいですか。"]),
            new("Which sounds good?", ["どちらがいいですか。"]),
            new("Omelet rice sounds good.", ["オムライスがいいです。"]),
            new("This time it's my treat too / This time I'll pay too (female/neutral gender)", ["今回も私のおごりです。", "今回も私の奢りです。"]),
            new("I'll have this lettuce salad.",["このレタスサラダにします。"]),
            new("Which dressing is good?", ["どのドレッシングがいいですか。"]),
            new("I would like some french fries. Sam, what will you have?", ["フライドポテトをお願いします。サムさんは何にしますか。"]),
            new("Sorry, I don't really like cucumbers.",["すみません、きゅうりはちょっと。", "すみません、胡瓜はちょっと。"]),
            new("Pork sausages sound good.", ["豚肉のソーセージがいいです。"]),
            new("I'll probably have this special.", ["多分このスペシャルにします。"]),
            new("soft and melty / creamy / smooth texture cheese.", ["とろとろのチーズ"]),
            new("I ate half of the hamburg steak", ["ハンバーグをはんぶん食べました。", "ハンバーグを半分食べました。"]),
            new("Would you like to eat half of the grapes?", ["ぶどうをはんぶんたべませんか。", "葡萄を半分食べませんか。"]),
            new("Let's go to a western-style restaurant", ["ようしょくレストランに行きましょう。", "洋食レストランに行きましょう。"]),
            ]),

        new("Section 4, unit 3 - Suggest things to do at the beach",[
            new("lemon", ["レモン"]),
            new("shaved ice, a sweet ice dessert often flavored with syrup", ["かきごおり", "かき氷"]),

            new("Would you like to swim somewhere this Wednesday?",["今週の水曜日にどこかで泳ぎませんか。", "今週の水曜日はどこかで泳ぎませんか。", "今週の水曜日どこかで泳ぎませんか。"]),
            new("Let's go next week", ["来週行きましょう。"]),
            new("Do you have plans on the eighth?", ["ようかによていはありますか。", "八日に予定はありますか。", "八日は予定はありますか。"]),
            new("Would you like to go somewhere?", ["どこかに行きませんか。"]),
            new("Let's go to a pool in Shibuya!", ["渋谷のプールに行きましょう。"]),
            new("Because it’s cheap, let’s go to the nearby beach.", ["安いので、近くの海に行きましょう。"]),
            new("Because the view is pretty, we should sit here.", ["けしきがきれいなので、ここにすわりましょう。","景色が綺麗なので、ここに座りましょう。"]),
            new("Because it's close,  let's walk to that spot over there.", ["近いので、あのばしょまであるきましょう。", "近いので、あの場所まで歩きましょう。"]),
            new("most / number one / the best in a group", ["いちばん", "一番"]),
            new("How about the nearest/closest beach?", ["一番近い海はどうですか。"]),
            new("The closest one is this beach.", ["一番近いのはこの海です。"]),
            new("Did you make sure to apply sunscreen?", ["ちゃんとひやけどめをぬりましたか。", "ちゃんと日焼け止めを塗りましたか。"]),
            new("I have brought ice. (I have brought some ice)", ["こおりをもってきました。", "氷を持ってきました。"]),
            new("I found a nice place.", ["いいばしょうをみつけました。", "いい場所を見つけました。"]),
            new("We should get straws.",["ストローを貰いましょう。"]),
            new("Do we need sunglasses?", ["サングラスは要りますか。", "サングラスはいりますか。"]),
            new("I need new sunglasses.", ["新しいサングラスがいります。", "新しいサングラスが要ります。"]),
            new("The locker room is there.", ["ロッカールームはそこです。", "ロッカールームはあそこです。"]),
            new("Because it's dirty, I'm going to wash my face later.", ["きたないので、あとでかおをあらいます。", "汚いので、後で顔を洗います。"]),
            new("Because it's late, we should go home in a bit.", ["遅いので、そろそろ家に帰りましょう。"]),
            new("I changed already.", ["おうきがえました。","もう着替えました。"]),
            new("We should quickly change / Let's change quickly.", ["はやくきがえましょう。", "速く着替えましょう。"]),
            new("I dropped my phone somewhere.", ["どこかでけいたいをおとしました。", "どこかで携帯を落としました。"]),
            new("It's fairly / reasonably / quite / pretty much close.", ["けっこう近いです。", "まあまあ近いです。", "結構近いです。", "かなり近いです。", "だいぶ近いです。", "すぐ近いです。"]),
            new("I want to do surfing.", ["サーフィンがしたいです。"]),
            ]
        ),

        new("Section 4, unit 2 - Describe health habits",[
            new("influenza", ["インフルエンザ"]),
            new("carrot", ["にんじん", "人参"]),
            new("yogurt", ["ヨーグルト"]),
            new("one time / once (per week/month/year, more formal or abstract)", ["いちど", "一度"]),
            new("one time / once (physical times/occurrences or actions, per day/event/attempt)", ["いっかい", "一回"]),
            new("once per day", ["うちにちにいっかい", "一日に一回"]),
            new("fried food", ["あげもの", "揚げ物"]),

            new("I do strength training almost every day.", ["ほとんど毎日きんトレをします。", "ほとんど毎日筋トレをします。"]),
            new("I don't smoke at all.", ["煙草は全然吸いません。", "煙草を全然吸いません。", "全然煙草を吸いません。", "全然煙草は吸いません。"]),
            new("I don't want to smoke anymore.", ["もう煙草を吸いたくないです。", "もう吸いたくないです。", "煙草をもう吸いたくないです。"]),
            new("I take medicine three times a day.", ["いちにちにさんかいくすりをのみます。", "一日に三回薬を飲みます。"]),
            new("I watch a movie once a week.", ["いっしゅうかんにいちどえいがをみます。", "一週間に一度映画を見ます。", "週に一度映画を見ます。", "週に一回映画を見ます。"]),
            new("I travel once a year.", ["いちねんにいちどりょこうします。", "一年に一度旅行します。"]),
            new("I do cycling four times a month", ["一か月に四回サイクリングをします。"]),
            new("I went to the clinic once last month. (casual count)", ["先月一回クリニックに行きました。", "先月は一回クリニックに行きました。", "先月クリニックに一回行きました。", "先月はクリニックに一回行きました。"]),
            new("Yesterday I made a reservation at a clinic.", ["昨日クリニックによやくをいれました。", "昨日クリニックに予約を入れました。"]),
            new("I have an appointment at the hospital next week.", ["来週病院の予約があります。", "来週は病院の予約があります。"]),
            new("My stomach hurts a bit", ["少しおなかが痛いです。", "少しお腹が痛いです。", "お腹が少し痛いです。"]),
            new("My throat kind of hurts", ["ちょっとのどが痛いです。", "ちょっと喉が痛いです。", "喉がちょっと痛いです。"]),
            new("I want to exercise more from now on.", ["これからもっとうんどうしたいです。", "これからもっと運動したいです。"]),
            new("I want to quit alcohol.",["おさけをやめたいです。", "お酒を辞めたいです。"]),
            new("I use my (portable) phone a lot late at night.", ["よなかにたくさんけいたいをつかいます。", "夜中にたくさん携帯を使います。", "夜中に携帯をたくさん使います。"]),
            new("I often work until late at night", ["よくよなかまでしごとします。", "よく夜中まで仕事します。", "夜中までよく仕事します。", "よく夜中まで仕事をします。", "夜中までよく仕事をします。"]),
            new("How often do you go to the gym?", ["どれぐらいジムに行きますか。", "どれくらいジムに行きますか。"]),
            new("I don't really like oily stuff (food)", ["あぶらっこい物はちょっと。", "油っこい物はちょっと。", "油っこい物はあまり好きじゃないです。"])
        ]),

        new("Section 4, unit 1 - Use past tense negative adjectives",[
            new("haunted house / haunted attraction", ["おばけやしき", "お化け屋敷"]),
            new("is crowded / is packed", ["こんでいます", "混んでいます"]),
            new("floor", ["ゆか", "床"]),
            new("scene / situation (in movie, story, real life)", ["シーン"]),
            new("hard (like stone or metal)", ["かたい", "硬い"]),
            new("main dish", ["メイン"]),

            new("Only the fruit was tasty.", ["くだものだけおいしかったです。", "果物だけ美味しかったです。", "果物だけは美味しかったです。"]),
            new("It was a very disappointing date, you know.", ["とてもざんねんなデートでしたね。", "とても残念なデートでしたね。", "デートはとても残念でしたね。"]),
            new("I met a nice person on this app last week.", ["先週このアプリでいい人に会いました。"]),
            new("I'll break up with my boyfriend soon.", ["もうすぐかれしとわかれます。", "もうすぐ彼氏と別れます。"]),
            new("I'm sure I'll find a lovelier partner.", ["きっともっとすてきなパートナーをみつけます。", "きっともっと素敵なパートナーを見つけます。"]),
            new("This time the date wasn't fun at all. My boyfriend hardly talked with me.", ["こんかいデートはぜんぜんたのしくなかったです。かれしは私とあまり話しませんでした。", "今回デートは全然楽しくなかったです。彼氏は私とあまり話しませんでした。"]),
            new("I had a fight with my new girlfriend.", ["新しいかのじょとけんかしました。", "新しい彼女と喧嘩しました。"]),
            new("There were other (of the same set) problems too.", ["ほかのもんだいもありました。", "他の問題もありました。"]),
            new("The acting was the worst.", ["えんぎはさいあくでした。", "演技は最悪でした。"]),
            new("We waited in a line for two hours.", ["れつでにじかんまちました。","列で二時間待ちました。"])

        ]),

        new("Section 3, unit 30 - Talk about your childhood",[
            new("When I a child", ["こどものとき", "子供の時"]),
            new("When I was six years old", ["ろくさいのとき", "六歳の時"]),
            new("When I was an elementary school student, I learned swimming in PE.", ["しょうがくせいのとき、たいいくですいえいをならいました。", "小学生の時、体育で水泳を習いました。"]),
            new("I’m glad I occasionally took swimming lessons when I was in kindergarten.", ["ようちえんのとき、たまにすいえいをならってよかったです。", "幼稚園の時、たまに水泳を習ってよかったです。"]),
            new("The uniform rules in my high school were strict.", ["こうこうのせいふくのきそくはきびしかったです。", "高校の制服の規則は厳しかったです。"]),
            new("I probably want to become a manga artist.", ["たぶんまんがかになりたいです。", "多分漫画家になりたいです。"]),
            new("When I was a middle school student, I participated in a boxing tournament.", ["ちゅうがくせいのとき、ボクシングのたいかいにでました。", "中学生の時、ボクシングの大会に出ました。"]),
            new("The high school students' uniforms were very cool.", ["こうこうせいのせいふくはとてもかっこよかったです。", "高校生の制服はとてもかっこよかったです。"]),
            new("I occasionally go jogging in a park in the suburbs.", ["たまにこうがいのこうえんでジョギングをします。", "たまに郊外の公園でジョギングをします。"]),
            new("The art teacher was occasionally strict.", ["びじゅつのせんせいはたまにきびしかったです。", "美術の先生はたまに厳しかったです。"]),
            new("When I was in kindergarten, I occasionally received candy from my teacher.", ["ようちえんのとき、たまにせんせいからあめをもらいました。", "幼稚園の時、たまに先生からあめを貰いました。", "幼稚園の時、たまに先生から飴を貰いました。"]),
            ]),
        new("Section 3, unit 29 - Complain about a hotel",[
            new("advertisement / commercial / ad", ["こうこく", "広告"]),
            new("curtain", ["カーテン"]),
            new("cockroach", ["ゴキブリ"]),
            new("thin / weak / light (flavor or color)", ["うすい", "薄い"]),
            new("lukewarm / tepid", ["ぬるい"]),
            new("fruit", ["くだもの", "果物"]),
            new("cereal", ["シリアル"]),
            new("sticky / greasy / clingy", ["ベタベタ"]),
            new("bad / poor / wrong", ["わるい", "悪い"]),
            new("other / another / different (other of the same set)", ["ほかの", "他の", "他"]),
            new("other / another / different (other option, not necessarily same set)", ["べつの", "別の", "別"]),
            ]),
        new("Section 3, unit 28 - Describe health issues",[
            new("to put in / to insert / to add (object / reservation)", ["いれます", "入れます"]),
            new("What’s wrong? / What happened?", ["どうしましたか"]),
            new("It hurts / painful", ["いたい", "痛い"]),
            new("head", ["あたま", "頭"]),
            new("neck", ["くび", "首"]),
            new("electricity / electric / light", ["でんき", "電気"]),
            new("social media", ["えすえぬえす", "SNS"]),
            new("almost / mostly / nearly all", ["ほとんど"]),
            new("arm", ["うで", "腕"]),
            new("to fall / to tumble", ["ころびます", "転びます"]),
            new("to hit / to strike / to bump / to get hit", ["うちます", "打ちます"]),
            new("wound / cut / injury", ["きず", "傷"]),
            new("pharmacy / drugstore", ["やっきょく", "薬局"]),
            new("for a while / for some time", ["しばらく"]),
            new("to get better / to recover / to be fixed", ["なおります", "治ります"]),
            new("to paint / to apply / to spread", ["ぬります", "塗ります"]),

        ]),

        new("Section 3, unit 27 - Use past tense adjectives",[
            new("shelf", ["たな", "棚"]),
            new("husband (someone else's, medium polite, casual)", ["旦那さん"]),
            new("wife (someone else's, medium polite, casual)", ["奥さん"]),
            new("entrance / entryway / front door area of a house", ["げんかん", "玄関"]),
            new("to wear (lower body / feet)", ["はきます", "履きます"]),
            new("to wear (upper body / whole body)", ["きます", "着ます"]),
            new("whose", ["だれの", "誰の"]),
            new("gate", ["もん", "門"]),
            new("furniture", ["かぐ", "家具"]),
            new("between / space / interval / gap", ["あいだ", "間"]),
            new("vase", ["かびん", "花瓶"]),
            new("dining room / dining", ["ダイニング"]),
            new("handmade", ["てづくり", "手作り"]),
            new("wall", ["かべ", "壁"]),
            ]),

        new("Archive",[
            new("foreign language", ["外国語"]),
            new("onion", ["玉ねぎ"]),
            new("sugar", ["砂糖"]),
            new("potato", ["じゃがいも"]),
            new("wheat flour / flour", ["小麦粉"]),

            new("life / daily life", ["生活"]),
            new("traditional flooring", ["畳"]),
            new("late / slowly (adverbial / connective form)", ["遅く"]),

            new("to turn on / to attach", ["付けます"]),
            new("to arrive / will arrive", ["着きます"]),
            new("merch", ["グッズ"]),
            new("to go out / head out (outing/activity)", ["出掛けます"]),
            new("to leave / to exit / to come out (general verb for exiting a place)", ["出ます"]),
            new("pay, going to pay, will pay", ["払います"]),
            new("enter/enroll/join", ["入ります"]),

            new("many / numerous / a large number of", ["多い"]),
            new("front desk", ["受付"]),
            new("comfortable / pleasant / cozy", ["快適"]),
            new("drawer (in desk, cabinet, furniture)", ["引き出し"]),
            ]),
        new("Practice sentences",[
            new("Let's get off the train at the next station.",["次の駅で電車を降りましょう"]),
            new("My younger brother also enrolled at a university last year.",["去年弟も大学に入りました。"]),
            new("The office is on the tenth floor of the building.", ["オフィスは建物の十階です。", "オフィスは建物の十階にあります。"]),
            new("I don't want to talk with the company people.", ["会社の人と話したくないです。"]),
            new("The nearby supermarket closes at six o'clock.", ["近くのスーパーは六時に閉まります。"]),
            new("Where did you get hit?", ["どこを打ちましたか。"]),
            new("Do you have free time?", ["ひまな時間がありますか。", "暇な時間がありますか。", "暇な時間はありますか。"]),
            new("I'm still at home", ["まだ家にいます。"]),
            new("How do we get to the neighboring town?", ["隣の町までどうやって行きますか。"]),
            new("I moved from the countryside to a city (town/neighborhood).", ["田舎から町に引っ越しました。"]),
            new("I will be busy on July 3rd.", ["七月三日は忙しいです。"]),
            new("I will work on August 10th. (in general, usually part of job)", ["八月十日は働きます。", "八月十日に働きます。"]),
            new("I don't want to get out of bed until tomorrow.", ["明日までベッドから出たくないです。"]),
            new("When did you catch a cold?", ["いつ風邪を引きましたか。"]),
            new("My boyfriend was one hour late.", ["かれしは一時間おくれました。", "彼氏は一時間遅れました。"]),
            new("I'm leaving the house now. (From now, I leave the house.)", ["今から家を出ます。"]),
            new("How old are you turning next week?", ["来週何歳になりますか。", "来週は何歳になりますか。"]),
            new("The shuttle was delayed.", ["シャトルバスは遅れました。"]),
            new("(My) major was chinese literature.", ["専攻は中国文学でした。"]),
            new("I don't want to wake up early.", ["早くおきたくないです。", "早く起きたくないです。"]),
            new("How many tables are there in the room? (As for in the room, tables — how many exist?)", ["部屋にはテーブルがいくつありますか", "部屋にテーブルがいくつありますか。", "部屋にテーブルはいくつありますか。"]),
            new("Would you like to eat somewhere?", ["どこかで食べませんか。"]),
            new("Would you like to eat at a restaurant somewhere?", ["どこかのレストランで食べませんか。", "どこかのレストランに食べに行きませんか。", "どこかのレストランに行って食べませんか。"]),
            new("Where are (we) going?", ["どこに行きますか。", "どこへ行きますか。", "どこ行くの。"]),
            new("(We) slept on the traditional flooring.", ["畳で寝ました。"]),
            new("(I'm) going to rest for a while", ["しばらく休みます", "少し休みます", "ちょっと休みます", "休ませていただきます", "少しの間休みます", "しばらくの間休みます", "ちょっとの間休みます"]),
            new("(I) want to get well soon.", ["早く元気になりたいです", "早く良くなりたいです"]),
            new("I will definitely book this room again.", ["必ずまたこの部屋を予約します", "また必ずこの部屋を予約します", "またこの部屋を必ず予約します"]),
            new("finally", ["やっと"]),
            new("I came here by train", ["電車でここに来ました", "電車でここまで来ました"]),
            new("Did (you) oversleep?", ["寝坊しましたか"]),
        ]),
    ];

}
