namespace GlossaryTrainer.Models;

internal static class GlossaryRepo
{
    //new("", ["", ""]),
    public static List<Glossary> Load()
    =>
    [
    new("Section 4, unit 12 - Discuss a meal", [
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),

            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
        ]),

    new("Section 4, unit 11 - Communicate at a store", [
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            new("meat bun", ["肉まん"]),
            new("to warm/heat", ["あたためます", "温めます"]),
            new("to push/press (for buttons, doors, or stamps/seals)", ["おします", "押します"]),
            new("instant cup noodles / cup ramen", ["カップラーメン"]),
            new("to pull out/take out/withdraw (literally/figuratively, money or eliciting something)", ["ひきだします", "引き出します"]),
            new("fermented soybeans", ["なっとう", "納豆"]),
            new("copy machine", ["コピーき", "コピー機"]),


            new("You can do it at that store over there.", ["あの店で出来ます。"]),
            new("I will copy the notebook.", ["ノートをコピーします。"]),
            new("It's open 24 hours", ["二十四時間あいています。", "二十四時間開いています。"]),
            new("It's open until ten.", ["十時まであいています。", "十時まで開いています。"]),
            new("That convenience store over there is open now.", ["あのコンビニは今あいています。", "あのコンビニは今開いています。"]),
            new("Open 24 hours / open 24 hours a day. (common for shops)", ["二十四時間えいぎょうしています。", "二十四時間営業しています。"]),
            new("I want to buy a few drinks.", ["飲み物をいくつか買いたいです。"]),
            new("Got it / understood.", ["わかりました。"]),
            new("This way.", ["こちらです。"]),
            new("Can you scan it?", ["スキャン出来ますか。"]),
            new("Please wait a moment.　(with politeness prefix)", ["しょうしょうおまちください。", "少々お待ちください。"]),
            new("Can I also scan textbooks at the convenience store?", ["コンビニできょうかしょのスキャンも出来ますか。", "コンビニで教科書のスキャンも出来ますか。"]),
            new("I want to buy postage stamps.", ["きってが買いたいです。", "切手が買いたいです。"]),
            new("I need a bit of money later.", ["後で少しお金が要ります。"]),
            new("How much are you going to withdraw?", ["いくらひきだしますか。", "いくら引き出しますか。"]),
            new("I want to withdraw money.", ["お金をひきだしたいです。", "お金を引き出したいです。"]),
            new("It comes to 100 yen./it will be 100 yen.", ["百円になります。"]),
            new("Altogether it's 100 yen.", ["ぜんぶで百円になります。", "全部で百円になります。"]),
            new("I already (postage) stamped it.", ["もうきってをおしました。", "もう切手を押しました。"]),
            new("Should I warm up the beef bowl?", ["ぎゅうどんをあたためましょうか。", "牛丼を温めましょうか。"]),
            new("You press this button.", ["このボタンをおします。", "このボタンを押します。"]),
            new("Lemon chewing gum", ["レモンのガム"]),
            new("Here you go.", ["どうぞ。"]),
            new("I'm going to pay with my smartphone.", ["スマホではらいます。", "スマホで払います。"]),
            new("I want to pay with a credit card.", ["クレジットカードではらいたいです。", "クレジットカードで払いたいです。"]),
            new("Here you go, your change.", ["どうぞ、おつりです。"]),
            new("Here you go, your meat bun.", ["どうぞ、肉まんです。"]),
            new("I don't need a straw. (customer service situation, Polite and softer than 要りません)", ["ストローはだいじょうぶです。", "ストローは大丈夫です。"]),
            new("Do you have money now?", ["今お金をもっていますか。", "今お金を持っていますか。"]),
            new("A lot of money.", ["たくさんのお金。"]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
        ]),

        new("Section 4, unit 10 - Buy stationery", [
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            new("calendar", ["カレンダー"]),
            new("sticky notes", ["ふせん", "付箋"]),
            new("stapler", ["ホチキス"]),
            new("scissor", ["はさみ", "ハサミ"]),
            new("to prepare/to get ready/to make preparations", ["じゅんびをします", "準備をします"]),
            new("stationery / writing supplies / office supplies", ["ぶんぼうぐ", "文房具"]),


            new("I'm going to prepare for school", ["学校のじゅんびをします。", "学校の準備をします。"]),
            new("I am ready / preparations are done.", ["じゅんびが出来ました。", "準備が出来ました。"]),
            new("School begins next week.", ["学校は来週から始まります。"]),
            new("On which day are you going to school?", ["何日に学校に行きますか。"]),
            new("By the way, when is school?", ["ところで、学校はいつですか。"]),
            new("Do you need an eraser?", ["けしゴムはいりますか。", "消しゴムは要りますか。"]),
            new("I need coloured pencils.", ["色えんぴつがいります。", "色鉛筆が要ります。"]),
            new("This mechanical pencil is cute and cheap.", ["このシャーペンは可愛くて安いです。"]),
            new("Stylish design.", ["お洒落なデザイン。"]),
            new("Those scissors are lightweight and cheap.", ["そのハサミはかるくて安いです。", "そのハサミは軽くて安いです。"]),
            new("It's an expensive and pretty notebook.", ["高くて綺麗なノートです。"]),
            new("This scissor is cheap and pretty.", ["このハサミは安くて綺麗です。"]),
            new("This stapler is expensive, but cool.", ["このホチキスは高いけど、かっこいいです。"]),
            new("thick notebook", ["あついノート", "厚いノート"]),
            new("I'll probably go with that stapler.", ["多分そのホチキスにします。"]),
            new("I want a cheap and cute calendar.", ["安くて可愛いカレンダーが欲しいです。"]),
            new("It's a hundred yen off　(it's 100 yen discount)", ["百円びきです。", "百円引きです。"]),
            new("These sticky notes are half price.", ["このふせんははんがくです。", "この付箋は半額です。"]),
            new("Which store's colored pencils are good?", ["どの店の色鉛筆がいいですか。"]),
            new("Because this store's sticky notes are cheap and good, I will buy a lot.", ["この店のふせんは安くていいので、たくさん買います。", "この店の付箋は安くていいので、たくさん買います。"]),
            new("I will write this year’s schedule on this calendar.", ["このカレンダーに今年のスケジュールを書きます。", ""]),
            ]
        ),

        new("Section 4, unit 9 - Desribe a recent date",[
            new("pudding", ["プリン"]),
            new("fishing", ["つり", "釣り"]),
            new("license / permit / certification", ["めんきょ", "免許"]),
            
            new("We text everyday.", ["毎日メールします。"]),
            new("Kai can drive.", ["かいさんは運転が出来ます。"]),
            new("Can Ken play golf?", ["けんさんはゴルフが出来ますか。"]),
            new("Ken has has a red car.", ["けんさんは赤い車を持っています。"]),
            new("Erika is good at table tennis.", ["エリカさんはたっきゅうがとくいです。", "エリカさんは卓球が得意です。"]),
            new("Sam's hobby is table tennis.", ["サムさんの趣味は卓球です。"]),
            new("The next date is on the twentieth.", ["つぎのデートははつかです。", "次のデートは二十日です。"]),
            new("July the twentieth is good.", ["七月はつかがいいです。", "七月二十日がいいです。"]),
            new("We're going to Shibuya to eat lunch.", ["渋谷に昼ご飯を食べに行きます。"]),
            new("Hana uses a lot of spices.", ["花さんはスパイスをたくさん使います。"]),
            new("This wednesday. Next wednesday.", ["今週の水曜日。来週の水曜日。"]),
            new("I have a lot of sports equipment.", ["スポーツようひんをたくさんもっています。", "スポーツ用品をたくさん持っています。"]),
            ]),

        new("Section 4, unit 8 - Talk about classes at university",[
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            new("to choose / to select / to pick", ["えらびます", "選びます"]),
            new("by all means/definitely/certainly/please do (strongly encourage/express desire)", ["ぜひ", "是非"]),
            new("theater / drama / stage play", ["えんげき", "演劇"]),
            new("international student", ["りゅうがくせい", "留学生"]),
            new("Europe", ["ヨーロッパ"]),
            new("media center/library/resource center", ["メディアセンター"]),
            new("programming language", ["プログラミングげんご", "プログラミング言語"]),
            new("textbook", ["きょうかしょ", "教科書"]),
            new("economics", ["けいざいがく", "経済学"]),
            new("biology", ["せいぶつがく", "生物学"]),
            new("to finish, to end, to be over", ["おわります", "終わります"]),
            new("this semester / the current school term", ["こんがっき", "今学期"]),
            new("next semester / the next school term", ["らいがっき", "来学期"]),
            new("to receive / to take (exam/lesson/test) / to accept", ["うけます", "受けます"]),

            new("Professor Tanaka is on campus once a week. (casual count)", ["田中先生は週に一回キャンパスにいます。"]),
            new("How many history students are there?", ["歴史の学生は何人いますか。"]),
            new("There are 11 literature students.", ["ぶんがくのがくせい[が/が]十一人います。", "文学の学生が十一人います。", "文学の学生は十一人います。"]),
            new("Are you finished with the history assignment?", ["れきしのかだいはおわりましたか。", "歴史の課題は終わりましたか。"]),
            new("The teacher is strict, but nice.", ["先生は厳しいけど、優しいです。"]),
            new("Office hours are from 10 o'clock on Thursday.", ["オフィスアワーは木曜日の十時からです。"]),
            new("I have a business class twice a week. (casual, straightforward count)", ["週に二回ビジネスのじゅぎょうがあります。", "週に二回ビジネスの授業があります。"]),
            new("We're doing biology homework as a group.", ["グループでせいぶつがくのしゅくだいをします。", "グループで生物学の宿題をします。"]),
            new("We often practice Spanish as a group", ["よくグループでスペイン語をれんしゅうします。", "よくグループでスペイン語を練習します。"]),
            new("I occasionally practice Japanese with my classmate.", ["たまにクラスメイトと日本語をれんしゅうします。", "たまにクラスメイトと日本語を練習します。"]),
            new("The economics assignments are difficult, but classes are fun.", ["けいざいがくのかだいはむずかしいけど、じゅぎょうはたのしいです。", "経済学の課題は難しいけど、授業は楽しいです。"]),
            new("economics textbook (published, printed, sold book)", ["けいざいがくのきょうかしょ", "経済学の教科書"]),
            new("Inside the media center is quiet and comfortable/cozy.", ["メディアセンターの中はしずかでかいてきです。", "メディアセンターの中は静かで快適です。"]),
            new("How's next month's schedule?", ["来月のスケジュールはどうですか。"]),
            new("What are you going to study next semester?", ["らいがっき何をべんきょうしますか。", "来学期何を勉強しますか。"]),
            new("Which classes did you choose?", ["どのじゅぎょうをえらびましたか。", "どの授業を選びましたか。"]),
            new("We should definitely do assignments together next time.", ["こんどぜひ一緒にかだいをしましょう。", "こんど是非一緒に課題をしましょう。"]),
            new("I don't want to do the programming homework.", ["プログラミングのしゅくだいはしたくないです。", "プログラミングの宿題はしたくないです。", "プログラミングの宿題をしたくないです。"]),
            new("I want to study abroad in Germany.", ["ドイツにりゅうがくしたいです。","ドイツに留学したいです。"]),
            ]),

        new("Section 4, unit 7 - Connect two adjectives",[
            new("amazing / incredible / wow / awesome", ["すごい", "凄い"]),
            new("the best / supreme / awesome / top-notch", ["さいこう", "最高"]),
            new("cook (head chef / someone skilled in cooking)", ["シェフ"]),
            new("healthy", ["ヘルシー"]),
            new("apartment building / condominium", ["マンション"]),
            new("rooftop", ["おくじょう", "屋上"]),
            new("website", ["サイト"]),
            new("to look up / investigate / check / examine", ["しらべます", "調べます"]),

            new("I will look up the menu.", ["メニューをしらべます。", "メニューを調べます。"]),
            new("That restaurant is on the third floor. (emphasize location)", ["そのレストランは三階にあります。"]),
            new("Which floor is the restaurant on? (emphasize location)", ["レストランは何階にありますか。"]),
            new("This pizza shop is lovely and famous.", ["このピザ屋は素敵で有名です。"]),
            new("The staff here is always the best.", ["ここのスタッフはいつもさいこうです。", "ここのスタッフはいつも最高です。"]),
            new("It gets crowded on Fridays.", ["金曜日はこみます。", "金曜日は混みます。", "金曜日は込みます。"]),
            new("Around what time does it get crowded?", ["何時ごろこみますか。", "何時ごろ混みますか。", "何時ごろ込みますか。"]),
            new("Does it get crowded around twelve?", ["十二時ごろはこみますか。", "十二時ごろは混みますか。", "十二時ごろは込みますか。", "十二時ごろ混みますか。", "十二時ごろ込みますか。"]),
            new("I'll check on a website.", ["サイトでチェックします。"]),
            new("That's so, isn't it? / Let me see / Hmm, yes / right",["そうですね。"] ),
            new("The cucumber salad there is famous.", ["そこの胡瓜サラダは有名です。"]),
            new("Let's go with that stylish vegetarian restaurant.", ["そのお洒落なベジタリアンレストランにしましょう。"]),
            new("I'm going to make a reservation for 8 o'clock.", ["八時の予約を入れます。"]),
            new("What time should we make a reservation for?", ["何時の予約を入れましょうか。"]),
            new("Right, it's cheap so let's eat at this sushi restaurant.", ["そうですね、安いのでこの寿司屋で食べましょう。"]),
            ]),

        new("Section 4, unit 6 - Make plans to go out",[
            new("actress", ["じょゆう", "女優"]),
            new("genre", ["ジャンル"]),
            new("arcade / game center", ["ゲームセンター"]),
            new("parfait (dessert, layers of ice cream, fruit, syrup, whipped cream)", ["パフェ"]),
            new("bowling", ["ボウリング"]),
            new("earring", ["イヤリング"]),
            new("shopping mall", ["ショッピングモール"]),
            new("tower", ["タワー"]),
            new("Japanese-style pub / bar / casual drinking restaurant", ["いざかや", "居酒屋"]),
            
            new("The ending of the movie was sad. (focus on identifying what was sad)", ["えいがのけつまつがかなしかったです。", "映画の結末が悲しかったです。"]),
            new("Would you like to go see a comedy movie?", ["コメディえいがをみに行きませんか。", "コメディ映画を見に行きませんか。"]),
            new("Would you like to go eat a parfait?", ["パフェを食べに行きませんか。"]),
            new("After the movie, would you like to go drink?", ["映画の後、飲みに行きませんか。"]),
            new("Let's go eat caramel somewhere.", ["どこかでキャラメルを食べに行きましょう。"]),
            new("Would you like to go to Ueno to buy books?", ["上野に本を買いに行きませんか。"]),
            new("After that, let's go to Shinjuku to hang out together.", ["その後、いっしょにしんじゅくにあそびに行きましょう。", "その後、一緒に新宿に遊びに行きましょう。"]),
            new("Yes, sounds good. (seeking agreement or confirmation)", ["はい、いいですね。"]),
            new("That also sounds good. (seeking agreement or confirmation)", ["それもいいですね。"]),
            new("No, it's not good at all.", ["いいえ、ぜんぜんよくないです。", "いいえ、全然よくないです。"]),
            new("There's a nice movie theater south of the station.", ["駅の南にいい映画館があります。"]),
            new("The movie theater south of the department store is cheap.", ["デパートの南の映画館は安いです。"]),
            new("Tokyo’s night view is pretty.", ["東京の夜のけしきはきれいです。", "東京の夜の景色は綺麗です。"]),

            ]
        ),

        new("Section 4, unit 5 - Describe a wedding",[
            new("I rented a limousine with my family.", ["かぞくとリムジンをかりました。", "家族とリムジンを借りました。"]),
            new("The venue wasn't big.", ["かいじょうは大きくなかったです。", "会場は大きくなかったです。"]),
            new("The venue wasn't close.", ["かいじょうは近くなかったです。", "会場は近くなかったです。"]),
            new("The wedding decorations weren't pretty.", ["けっこんしきのデコレーションはきれいじゃなかったです。", "結婚式のデコレーションは綺麗じゃなかったです。"]),
            new("The bride's dress was elegant.", ["しんぷのドレスうつくしかったです。", "新婦のドレスは美しかったです。"]),
            new("The guests were not lively.", ["ゲストはにぎやかじゃなかったです。", "ゲストは賑やかじゃなかったです。"]),
            new("I greeted Ken's father.", ["けんさんのお父さんにあいさつしました。", "けんさんのお父さんに挨拶しました。"]),
            new("The groom's relatives weren't nice.", ["しんろうのしんせきはやさしくなかったです。", "新郎の親戚は優しくなかったです。"]),
            new("The carpet/rug's color was hideous.", ["カーペットの色はダサかったです。"]),
            new("The cake's flavor was very weird.", ["ケーキのあじはとてもへんでした。", "ケーキの味はとても変でした。"]),
            new("The tables were low.", ["テーブルはひくかったです。", "テーブルは低かったです。"]),
            new("The jazz band's performance was terrible.", ["ジャズバンドのパフォーマンスはひどかったです。", "ジャズバンドのパフォーマンスは酷かったです。"]),
            new("The singer's song was terrible.", ["かしゅのうたはひどかったです。", "歌手の歌は酷かったです。"]),
            new("Because the limousine was expensive, we took a bus.", ["リムジンは高かったので、バスに乗りました。"]),
            new("After the meal, there was a boring speech.", ["ご飯の後、詰まらないスピーチがありました。"]),
            new("The day before yesterday, I did nothing all day.", ["おとといいちにちじゅう何もしませんでした。", "一昨日一日中何もしませんでした。"]),
            new("I went to the wedding by limo with some other people.", ["ほかの人とリムジンでけっこんしきに行きました。", "他の人とリムジンで結婚式に行きました。"]),

            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", []),
            ]
        ),

        new("Section 4, unit 4 - Discuss what to eat",[
            new("family restaurant (casual chain restaurant)", ["ファミレス"]),
            new("drink bar / self-service beverage station", ["ドリンクバー"]),
            new("broccoli", ["ブロッコリー"]),
            new("expression said before meals / I humbly receive (this food) / let's eat", ["いただきます", "頂きます"]),
            new("mayonnaise", ["マヨネーズ"]),
            new("half / halfway. Commonly used for dividing things or amounts, as well as time or distance", ["はんぶん", "半分"]),


            new("Which do you prefer, seafood or meat? / Seafood or meat, which is better?", ["シーフードと肉、どちらがいいですか。"]),
            new("Which sounds good?", ["どちらがいいですか。"]),
            new("Omelet rice sounds good.", ["オムライスがいいです。"]),
            new("This time it's my treat too / This time I'll pay too", ["今回も私のおごりです。", "今回も私の奢りです。"]),
            new("I'll have this lettuce salad.",["このレタスサラダにします。"]),
            new("Which dressing is good?", ["どのドレッシングがいいですか。"]),
            new("I would like some french fries. Sam, what will you have?", ["フライドポテトをお願いします。サムさんは何にしますか。"]),
            new("Sorry, I don't really like cucumbers.",["すみません、きゅうりはちょっと。", "すみません、胡瓜はちょっと。"]),
            new("Pork sausages sound good.", ["豚肉のソーセージがいいです。"]),
            new("I'll probably have this special.", ["多分このスペシャルにします。"]),
            new("soft and melty / creamy / smooth texture cheese.", ["とろとろのチーズ"]),
            new("I ate half of the hamburg steak", ["ハンバーグをはんぶん食べました。", "ハンバーグを半分食べました。"]),
            new("Would you like to eat half of the grapes?", ["ぶどうをはんぶんたべませんか。", "葡萄を半分食べませんか。"]),
            new("Let's go to a western-style restaurant", ["ようしょくレストランに行きましょう。", "洋食レストランに行きましょう。"]),

            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            ]),

        new("Section 4, unit 3 - Suggest things to do at the beach",[
            new("lemon", ["レモン"]),
            new("shaved ice, a sweet ice dessert often flavored with syrup", ["かきごおり", "かき氷"]),

            new("Would you like to swim somewhere this wednesday?",["今週の水曜日にどこかに泳ぎませんか。"]),
            new("Let's go next week", ["来週行きましょう。"]),
            new("Do you have plans on the eighth?", ["ようかによていはありますか。", "八日に予定はありますか。"]),
            new("Would you like to go somewhere?", ["どこかに行きませんか。"]),
            new("Let's go to a pool in Shibuya!", ["渋谷のプールに行きましょう。"]),
            new("Because it’s cheap, let’s go to the nearby beach.", ["安いので、近くの海に行きましょう。"]),
            new("Because the view is pretty, we should sit here.", ["けしきがきれいなので、ここにすわりましょう。","景色が綺麗なので、ここに座りましょう。"]),
            new("Because it's close,  let's walk to that spot over there.", ["近いので、あのばしょまであるきましょう。", "近いので、あの場所まで歩きましょう。"]),
            new("most / number one / the best in a group", ["いちばん", "一番"]),
            new("How about the nearest/closest beach?", ["一番近い海はどうですか。"]),
            new("The closest one is this beach.", ["一番近いのはこの海です。"]),
            new("Did you make sure to apply sunscreen?", ["ちゃんとひやけどめをぬりましたか。", "ちゃんと日焼け止めを塗りましたか。"]),
            new("I have brought ice. (I have brought some ice)", ["こおりをもってきました。", "氷を持ってきました。"]),
            new("I found a nice place.", ["いいばしょうをみつけました。", "いい場所を見つけました。"]),
            new("We should get straws.",["ストローを貰いましょう。"]),
            new("Do we need sunglasses?", ["サングラスは要りますか。", "サングラスはいりますか。"]),
            new("I need new sunglasses.", ["新しいサングラスがいります。", "新しいサングラスが要ります。"]),
            new("The locker room is there.", ["ロッカールームはそこです。"]),
            new("Because it's dirty, I'm going to wash my face later.", ["きたないので、あとでかおをあらいます。", "汚いので、後で顔を洗います。"]),
            new("Because it's late, we should go home in a bit.", ["遅いので、そろそろ家に帰りましょう。"]),
            new("I changed already.", ["おうきがえました。","もう着替えました。"]),
            new("We should quickly change / Let's change quickly.", ["はやくきがえましょう。", "速く着替えましょう。"]),
            new("I dropped my phone somewhere.", ["どこかでけいたいをおとしました。", "どこかで携帯を落としました。"]),
            new("It's fairly / reasonably / quite / pretty much close.", ["けっこう近いです。", "結構近いです。"]),
            new("I want to go surfing.", ["サーフィンがしたいです。"]),
            ]
        ),

        new("Section 4, unit 2 - Describe health habits",[
            new("influenza", ["インフルエンザ"]),
            new("carrot", ["にんじん", "人参"]),
            new("yogurt", ["ヨーグルト"]),
            new("one time / once (per week/month/year, more formal or abstract)", ["いちど", "一度"]),
            new("one time / once (physical times/occurrences or actions, per day/event/attempt)", ["いっかい", "一回"]),
            new("once per day", ["うちにちにいっかい", "一日に一回"]),
            new("fried food", ["あげもの", "揚げ物"]),

            new("I do strength training almost every day.", ["ほとんど毎日きんトレをします。", "ほとんど毎日筋トレをします。"]),
            new("I don't smoke at all.", ["たばこはぜんぜんすいません。", "煙草は全然吸いません。"]),
            new("I don't want to smoke anymore.", ["もうたばこをすいたくないです。", "もう煙草を吸いたくないです。", "もう吸いたくないです。"]),
            new("I take medicine three times a day.", ["いちにちにさんかいくすりをのみます。", "一日に三回薬を飲みます。"]),
            new("I watch a movie once a week.", ["いっしゅうかんにいちどえいがをみます。", "一週間に一度映画を見ます。"]),
            new("I travel once a year.", ["いちねんにいちどりょこうします。", "一年に一度旅行します。"]),
            new("I do cycling four times a month", ["一か月に四回サイクリングをします。"]),
            new("I went to the clinic once last month.", ["先月一回クリニックに行きました。"]),
            new("Yesterday I made a reservation at a clinic.", ["昨日クリニックによやくをいれました。", "昨日クリニックに予約を入れました。"]),
            new("I have an appointment at the hospital next week.", ["来週びょういんのよやくがあります。", "来週病院の予約があります。"]),
            new("My stomach hurts a bit", ["少しおなかが痛いです。", "少しお腹が痛いです。"]),
            new("My throat kind of hurts", ["ちょっとのどが痛いです。", "ちょっと喉が痛いです。"]),
            new("I want to exercise more from now on.", ["これからもっとうんどうしたいです。", "これからもっと運動したいです。"]),
            new("I want to quit alcohol.",["おさけをやめたいです。", "お酒を辞めたいです。"]),
            new("I use my (portable) phone a lot late at night.", ["よなかにたくさんけいたいをつかいます。", "夜中にたくさん携帯を使います。", "夜中に携帯をたくさん使います。"]),
            new("I quite often work until late at night", ["けっこうよなかまでしごとします。", "結構夜中まで仕事します。"]),
            new("How often do you go to the gym?", ["どれぐらいジムに行きますか。"]),
            new("I don't really like oily stuff (food)", ["あぶらっこい物はちょっと。", "油っこい物はちょっと。"])
        ]),

        new("Section 4, unit 1 - Use past tense negative adjectives",[
            //new("To have an argument, to bicker, to get into a fight",["けんかします", "喧嘩します"]),
            //new("the worst　/ worst case scenario", ["さいあく", "最悪"]),
            //new("This time, on this occasion, this round", ["こんかい", "今回"]),
            //new("line / queue", ["れつ", "列"]),
            //new("acting / performance", ["えんぎ", "演技"]),
            //new("only (no more than this)", ["だけ"]),
            //new("disappointing", ["ざんねん", "残念"]),
            //new("app (smart phone / computer app)", ["アプリ"]),
            //new("to break up (couple) / to part ways (goodbye's after hanging out)", ["わかれます", "別れます"]),
            //new("surely / definitely / most likely", ["きっと"]),
            //new("problem / question / issue", ["もんだい", "問題"]),
            new("haunted house / haunted attraction", ["おばけやしき", "お化け屋敷"]),
            new("is crowded / is packed", ["こんでいます", "混んでいます"]),
            new("floor", ["ゆか", "床"]),
            new("scene / situation (in movie, story, real life)", ["シーン"]),
            new("hard (like stone or metal)", ["かたい", "硬い"]),
            new("main dish", ["メイン"]),

            new("Only the fruit was tasty.", ["くだものだけおいしかったです。", "果物だけ美味しかったです。"]),
            new("It was a very disappointing date, you know.", ["とてもざんねんなデートでしたね。", "とても残念なデートでしたね。", "デートはとても残念でしたね。"]),
            new("I met a nice person on this app last week.", ["先週このアプリでいい人に会いました。"]),
            new("I'll break up with my boyfriend soon.", ["もうすぐかれしとわかれます。", "もうすぐ彼氏と別れます。"]),
            new("I'm sure I'll find a lovelier partner.", ["きっともっとすてきなパートナーをみつけます。", "きっともっと素敵なパートナーを見つけます。"]),
            new("This time the date wasn't fun at all. My boyfriend hardly talked with me.", ["こんかいデートはぜんぜんたのしくなかったです。かれしは私とあまり話しませんでした。", "今回デートは全然楽しくなかったです。彼氏は私とあまり話しませんでした。"]),
            new("I had a fight with my new girlfriend.", ["新しいかのじょとけんかしました。", "新しい彼女と喧嘩しました。"]),
            new("There were other (of the same set) problems too.", ["ほかのもんだいもありました。", "他の問題もありました。"]),
            new("The acting was the worst.", ["えんぎはさいあくでした。", "演技は最悪でした。"]),
            new("We waited in a line for two hours.", ["れつでにじかんまちました。","列で二時間待ちました。"])

        ]),

        new("Section 3, unit 30 - Talk about your childhood",[
            //new("candy", ["あめ", "飴"]),
            //new("suburb", ["こうがい", "郊外"], Tooltip.Kougai),
            //new("occasionally; once in a while; sometimes", ["たまに", "偶に"], Tooltip.Tamani),
            //new("To learn; to take lessons", ["ならいます", "習います"], Tooltip.Naraimasu),
            //new("kindergarten", ["ようちえん", "幼稚園"]),
            //new("Elementary school student, grade 1->6, age 6-12", ["しょうがくせい", "小学生"], Tooltip.Shougakusei),
            //new("Middle school student, grade 7->9, age 12-15", ["ちゅうがくせい", "中学生"]),
            //new("High school student, grade 10-12, age 15-18", ["こうこうせい", "高校生"]),
            //new("Physical education, P.E.", ["たいいく", "体育"], Tooltip.Taiiku),
            //new("swimming as sport / school subject / general concept", ["すいえい", "水泳"], Tooltip.Suiei),
            //new("art (subject / field of study / generally (paintings, sculptures))", ["びじゅつ", "美術"]),
            //new("school uniform", ["せいふく", "制服"]),
            //new("Strict; severe; tough", ["きびしい","厳しい"]),
            //new("Was cool; was handsome; was stylish.", ["かっこよかった"]),
            //new("Convention; tournament (whole); meet; mass meeting.", ["たいかい", "大会"]),
            //new("Boxing", ["ボクシング"]),
            //new("Jogging", ["ジョギング"]),
            //new("karate", ["からて", "空手"]),

            new("When I a child", ["こどものとき", "子供の時"], Tooltip.KodomoNoToki),
            new("When I was six years old", ["ろくさいのとき", "六歳の時"]),
            new("When I was an elementary school student, I learned swimming in PE.", ["しょうがくせいのとき、たいいくですいえいをならいました。", "小学生の時、体育で水泳を習いました。"]),
            new("I’m glad I occasionally took swimming lessons when I was in kindergarten.", ["ようちえんのとき、たまにすいえいをならってよかったです。", "幼稚園の時、たまに水泳を習ってよかったです。"]),
            new("The uniform rules in my high school were strict.", ["こうこうのせいふくのきそくはきびしかったです。", "高校の制服の規則は厳しかったです。"]),
            new("I probably want to become a manga artist.", ["たぶんまんがかになりたいです。", "多分漫画家になりたいです。"]),
            new("When I was a middle school student, I participated in a boxing tournament.", ["ちゅうがくせいのとき、ボクシングのたいかいにでました。", "中学生の時、ボクシングの大会に出ました。"]),
            new("The high school students' uniforms were very cool.", ["こうこうせいのせいふくはとてもかっこよかったです。", "高校生の制服はとてもかっこよかったです。"]),
            new("I occasionally go jogging in a park in the suburbs.", ["たまにこうがいのこうえんでジョギングをします。", "たまに郊外の公園でジョギングをします。"]),
            new("The art teacher was occasionally strict.", ["びじゅつのせんせいはたまにきびしかったです。", "美術の先生はたまに厳しかったです。"]),
            new("When I was in kindergarten, I occasionally received candy from my teacher.", ["ようちえんのとき、たまにせんせいからあめをもらいました。", "幼稚園の時、たまに先生からあめを貰いました。", "幼稚園の時、たまに先生から飴を貰いました。"]),
            ]),
        new("Section 3, unit 29 - Complain about a hotel",[
            new("advertisement / commercial / ad", ["こうこく", "広告"], Tooltip.Koukoku),
            new("curtain", ["カーテン"], Tooltip.Kaaten),
            new("cockroach", ["ゴキブリ"], Tooltip.Gokiburi),
            new("thin / weak / light (flavor or color)", ["うすい", "薄い"], Tooltip.Usui),
            new("lukewarm / tepid", ["ぬるい"], Tooltip.Nurui),
            new("fruit", ["くだもの", "果物"], Tooltip.Kudamono),
            new("cereal", ["シリアル"]),
            new("sticky / greasy / clingy", ["ベタベタ"], Tooltip.Betabeta),
            new("bad / poor / wrong", ["わるい", "悪い"], Tooltip.Warui),
            new("other / another / different (other of the same set)", ["ほかの", "他の"], Tooltip.Hokano),
            new("other / another / different (other option, not necessarily same set)", ["べつの", "別の"]),
            ]),
        new("Section 3, unit 28 - Describe health issues",[
            new("to put in / to insert / to add (object / reservation)", ["いれます", "入れます"], Tooltip.Iremasu),
            new("What’s wrong? / What happened?", ["どうしましたか"], Tooltip.Doushimashitaka),
            new("It hurts / painful", ["いたい", "痛い"], Tooltip.Itai),
            new("head", ["あたま", "頭"], Tooltip.Atama),
            new("neck", ["くび", "首"], Tooltip.Kubi),
            new("electricity / electric / light", ["でんき", "電気"], Tooltip.Denki),
            new("social media", ["えすえぬえす", "SNS"], Tooltip.SNS),
            new("almost / mostly / nearly all", ["ほとんど"], Tooltip.Hotondo),
            new("arm", ["うで", "腕"], Tooltip.Ude),
            new("to fall / to tumble", ["ころびます", "転びます"], Tooltip.Korobimasu),
            new("to hit / to strike / to bump / to get hit", ["うちます", "打ちます"], Tooltip.Uchimasu),
            new("wound / cut / injury", ["きず", "傷"], Tooltip.Kizu),
            new("pharmacy / drugstore", ["やっきょく", "薬局"], Tooltip.Yakkyoku),
            new("for a while / for some time", ["しばらく"], Tooltip.Shibaraku),
            new("to get better / to recover / to be fixed", ["なおります", "治ります"], Tooltip.Naorimasu),
            new("to paint / to apply / to spread", ["ぬります", "塗ります"], Tooltip.Nurimasu),

        ]),

        new("Section 3, unit 27 - Use past tense adjectives",[
            new("shelf", ["たな", "棚"]),
            new("husband", ["だんなさん", "旦那さん"]),
            new("wife", ["おくさん", "奥さん"]),
            new("entrance / entryway / front door area of a house", ["げんかん", "玄関"]),
            new("to wear (lower body / feet)", ["はきます", "履きます"]),
            new("to wear (upper body / whole body)", ["きます", "着ます"]),
            new("whose", ["だれの", "誰の"]),
            new("gate", ["もん", "門"]),
            new("furniture", ["かぐ", "家具"]),
            new("between / space / interval / gap", ["あいだ", "間"]),
            new("vase", ["かびん", "花瓶"]),
            new("dining room / dining", ["ダイニング"]),
            new("handmade", ["てづくり", "手作り"]),
            new("wall", ["かべ", "壁"]),
            ]),

        new("Archive",[
            new("foreign language", ["がいこくご", "外国語"]),
            new("onion", ["たまねぎ", "玉ねぎ"]),
            new("sugar", ["さとう", "砂糖"]),
            new("potato", ["じゃがいも", "じゃがいも"]),
            new("wheat flour / flour", ["こむぎこ", "小麦粉"]),

            new("life / daily life", ["せいかつ", "生活"]),
            new("traditional flooring", ["たたみ", "畳"]),
            new("late / slowly", ["おそく", "遅く"]),

            new("to turn on / to attach", ["つけます", "付けます"]),
            new("to arrive / will arrive", ["つきます", "着きます"]),
            new("merch", ["グッズ", "グッズ"]),
            new("to go out / head out (outing/activity)", ["でかけます", "出かけます"]),
            new("to leave / to exit / to come out (general verb for exiting a place)", ["でます", "出ます"]),
            new("pay, going to pay, will pay", ["はらいます", "払います"]),
            new("enter/enroll/join", ["はいります", "入ります"]),

            new("many / numerous / a large number of", ["おおい", "多い"]),
            new("front desk", ["うけつけ", "受付"]),
            new("comfortable / pleasant / cozy", ["かいてき", "快適"]),
            new("drawer (in desk, cabinet, furniture)", ["ひきだし", "引き出し"]),
            ]),
        new("Practice sentences",[
            new("We should get off at the next station.",["つぎのえきでおりましょう。", "次の駅で降りましょう。"]),
            new("My younger brother also enrolled at a university last year.",["きょねんおとうともだいがくにはいりました。", "去年弟も大学に入りました。"]),
            new("The office is on the tenth floor of the building.", ["オフィスはたてもののじゅっかいです。", "オフィスは建物の十階です。"]),
            new("I don't want to talk with the company people.", ["かいしゃのひととはなしたくないです。", "会社の人と話したくないです。"]),
            new("The nearby supermarket closes at six o'clock.", ["ちかくのスーパーはろくじにしまります。", "近くのスーパーは六時に締まります。"]),
            new("Where did you get hit?", ["どこをうちましたか。", "どこを打ちましたか。"]),
            new("Do you have free time?", ["ひまな時間がありますか。", "暇な時間がありますか。"]),
            new("I'm still at home", ["まだ家にいます。"]),
            new("How do we get to the neighboring town?", ["となりのまちまでどうやって行きますか。", "隣の町までどうやって行きますか。"]),
            new("I moved from the countryside to a city (town/neighborhood).", ["いなかからとしにひっこしました。", "田舎から町に引っ越しました。"]),
            new("I will be busy on July 3rd.", ["七月三日はいそがしいです。", "七月三日は忙しいです。"]),
            new("I will work on August 10th. (in general, usually part of job)", ["八月十日[は/に]はたらきます。", "八月十日は働きます。", "八月十日に働きます。"]),
            new("I don't want to get out of bed until tomorrow.", ["明日までベッドから出たくないです。"]),
            new("When did you catch a cold?", ["いつかぜをひきましたか。", "いつ風邪を引きましたか。"]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
        ]),
    ];

}
