namespace GlossaryTrainer.Models;

internal static class GlossaryRepo
{
    //new("", ["", ""]),
    public static List<Glossary> Load()
    =>
    [
        new("Section 4, unit 2 - Describe health habits",[
            new("influenza", ["インフルエンザ"]),
            new("carrot", ["にんじん", "人参"]),
            new("yogurt", ["ヨーグルト"]),
            new("one time / once (per week/month/year, more formal or abstract)", ["いちど", "一度"]),
            new("one time / once (physical times/occurrences or actions, per day/event/attempt)", ["いっかい", "一回"]),
            new("once per day", ["うちにちにいっかい", "一日に一回"]),
            new("fried food", ["あげもの", "揚げ物"]),

            new("I do strength training almost every day.", ["ほとんど毎日きんトレをします。", "ほとんど毎日筋トレをします。"]),
            new("I don't smoke at all.", ["たばこはぜんぜんすいません。", "煙草は全然吸いません。"]),
            new("I don't want to smoke anymore.", ["もうたばこをすいたくないです。", "もう煙草を吸いたくないです。", "もう吸いたくないです。"]),
            new("I take medicine three times a day.", ["いちにちにさんかいくすりをのみます。", "一日に三回薬を飲みます。"]),
            new("I watch a movie once a week.", ["いっしゅうかんにいちどえいがをみます。", "一週間に一度映画を見ます。"]),
            new("I travel once a year.", ["いちねんにいちどりょこうします。", "一年に一度旅行します。"]),
            new("I do cycling four times a month", ["一か月に四回サイクリングをします。"]),
            new("I went to the clinic once last month.", ["先月一回クリニックに行きました。"]),
            new("Yesterday I made a reservation at a clinic.", ["昨日クリニックによやくをいれました。", "昨日クリニックに予約を入れました。"]),
            new("I have an appointment at the hospital next week.", ["来週びょういんのよやくがあります。", "来週病院の予約があります。"]),
            new("My stomach hurts a bit", ["少しおなかが痛いです。", "少しお腹が痛いです。"]),
            new("My throat kind of hurts", ["ちょっとのどが痛いです。", "ちょっと喉が痛いです。"]),
            new("I want to exercise more from now on.", ["これからもっとうんどうしたいです。", "これからもっと運動したいです。"]),
            new("I want to quit alcohol.",["おさけをやめたいです。", "お酒を辞めたいです。"]),
            new("I use my (portable) phone a lot late at night.", ["よなかにたくさんけいたいをつかいます。", "夜中にたくさん携帯を使います。", "夜中に携帯をたくさん使います。"]),
            new("I quite often work until late at night", ["けっこうよなかまでしごとします。", "結構夜中まで仕事します。"]),
            new("How often do you go to the gym?", ["どれぐらいジムに行きますか。"]),
            new("I don't really like oily stuff (food)", ["あぶらっこい物はちょっと。", "油っこい物はちょっと。"])
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
        ]),

        new("Section 4, unit 1 - Use past tense negative adjectives",[
            //new("To have an argument, to bicker, to get into a fight",["けんかします", "喧嘩します"]),
            //new("the worst　/ worst case scenario", ["さいあく", "最悪"]),
            //new("This time, on this occasion, this round", ["こんかい", "今回"]),
            //new("line / queue", ["れつ", "列"]),
            //new("acting / performance", ["えんぎ", "演技"]),
            //new("only (no more than this)", ["だけ"]),
            //new("disappointing", ["ざんねん", "残念"]),
            //new("app (smart phone / computer app)", ["アプリ"]),
            //new("to break up (couple) / to part ways (goodbye's after hanging out)", ["わかれます", "別れます"]),
            //new("surely / definitely / most likely", ["きっと"]),
            //new("problem / question / issue", ["もんだい", "問題"]),
            new("haunted house / haunted attraction", ["おばけやしき", "お化け屋敷"]),
            new("is crowded / is packed", ["こんでいます", "混んでいます"]),
            new("floor", ["ゆか", "床"]),
            new("scene / situation (in movie, story, real life)", ["シーン"]),
            new("hard (like stone or metal)", ["かたい", "硬い"]),
            new("main dish", ["メイン"]),

            new("Only the fruit was tasty.", ["くだものだけおいしかったです。", "果物だけ美味しかったです。"]),
            new("It was a very disappointing date, you know.", ["とてもざんねんなデートでしたね。", "とても残念なデートでしたね。", "デートはとても残念でしたね。"]),
            new("I met a nice person on this app last week.", ["先週このアプリでいい人に会いました。"]),
            new("I'll break up with my boyfriend soon.", ["もうすぐかれしとわかれます。", "もうすぐ彼氏と別れます。"]),
            new("I'm sure I'll find a lovelier partner.", ["きっともっとすてきなパートナーをみつけます。", "きっともっと素敵なパートナーを見つけます。"]),
            new("This time the date wasn't fun at all. My boyfriend hardly talked with me.", ["こんかいデートはぜんぜんたのしくなかったです。かれしは私とあまり話しませんでした。", "今回デートは全然楽しくなかったです。彼氏は私とあまり話しませんでした。"]),
            new("I had a fight with my new girlfriend.", ["新しいかのじょとけんかしました。", "新しい彼女と喧嘩しました。"]),
            new("There were other (of the same set) problems too.", ["ほかのもんだいもありました。", "他の問題もありました。"]),
            new("The acting was the worst.", ["えんぎはさいあくでした。", "演技は最悪でした。"]),
            new("We waited in a line for two hours.", ["れつでにじかんまちました。","列で二時間待ちました。"])

        ]),

        new("Section 3, unit 30 - Talk about your childhood",[
            //new("candy", ["あめ", "飴"]),
            //new("suburb", ["こうがい", "郊外"], Tooltip.Kougai),
            //new("occasionally; once in a while; sometimes", ["たまに", "偶に"], Tooltip.Tamani),
            //new("To learn; to take lessons", ["ならいます", "習います"], Tooltip.Naraimasu),
            //new("kindergarten", ["ようちえん", "幼稚園"]),
            //new("Elementary school student, grade 1->6, age 6-12", ["しょうがくせい", "小学生"], Tooltip.Shougakusei),
            //new("Middle school student, grade 7->9, age 12-15", ["ちゅうがくせい", "中学生"]),
            //new("High school student, grade 10-12, age 15-18", ["こうこうせい", "高校生"]),
            //new("Physical education, P.E.", ["たいいく", "体育"], Tooltip.Taiiku),
            //new("swimming as sport / school subject / general concept", ["すいえい", "水泳"], Tooltip.Suiei),
            //new("art (subject / field of study / generally (paintings, sculptures))", ["びじゅつ", "美術"]),
            //new("school uniform", ["せいふく", "制服"]),
            //new("Strict; severe; tough", ["きびしい","厳しい"]),
            //new("Was cool; was handsome; was stylish.", ["かっこよかった"]),
            //new("Convention; tournament (whole); meet; mass meeting.", ["たいかい", "大会"]),
            //new("Boxing", ["ボクシング"]),
            //new("Jogging", ["ジョギング"]),
            //new("karate", ["からて", "空手"]),

            new("When I a child", ["こどものとき", "子供の時"], Tooltip.KodomoNoToki),
            new("When I was six years old", ["ろくさいのとき", "六歳の時"]),
            new("When I was an elementary school student, I learned swimming in PE.", ["しょうがくせいのとき、たいいくですいえいをならいました。", "小学生の時、体育で水泳を習いました。"]),
            new("I’m glad I occasionally took swimming lessons when I was in kindergarten.", ["ようちえんのとき、たまにすいえいをならってよかったです。", "幼稚園の時、偶に水泳を習ってよかったです。"]),
            new("The uniform rules in my high school were strict.", ["こうこうのせいふくのきそくはきびしかったです。", "高校の制服の規則は厳しかったです。"]),
            new("I probably want to become a manga artist.", ["たぶんまんがかになりたいです。", "多分漫画家になりたいです。"]),
            new("When I was a middle school student, I participated in a boxing tournament.", ["ちゅうがくせいのとき、ボクシングのたいかいにでました。", "中学生の時、ボクシングの大会に出ました。"]),
            new("The high school students' uniforms were very cool.", ["こうこうせいのせいふくはとてもかっこよかったです。", "高校生の制服はとてもかっこよかったです。"]),
            new("I occasionally go jogging in a park in the suburbs.", ["たまにこうがいのこうえんでジョギングをします。", "偶に郊外の公園でジョギングをします。"]),
            new("The art teacher was occasionally strict.", ["びじゅつのせんせいはたまにきびしかったです。", "美術の先生は偶に厳しかったです。"]),
            new("When I was in kindergarten, I occasionally received candy from my teacher.", ["ようちえんのとき、たまにせんせいからあめをもらいました。", "幼稚園の時、偶に先生からあめを貰いました。", "幼稚園の時、偶に先生から飴を貰いました。"]),
            ]),
        new("Section 3, unit 29 - Complain about a hotel",[
            new("advertisement / commercial / ad", ["こうこく", "広告"], Tooltip.Koukoku),
            new("curtain", ["カーテン"], Tooltip.Kaaten),
            new("cockroach", ["ゴキブリ"], Tooltip.Gokiburi),
            new("thin / weak / light (flavor or color)", ["うすい", "薄い"], Tooltip.Usui),
            new("lukewarm / tepid", ["ぬるい"], Tooltip.Nurui),
            new("fruit", ["くだもの", "果物"], Tooltip.Kudamono),
            new("cereal", ["シリアル"]),
            new("sticky / greasy / clingy", ["ベタベタ"], Tooltip.Betabeta),
            new("bad / poor / wrong", ["わるい", "悪い"], Tooltip.Warui),
            new("other / another / different (other of the same set)", ["ほかの", "他の"], Tooltip.Hokano),
            new("other / another / different (other option, not necessarily same set)", ["べつの", "別の"]),
            ]),
        new("Section 3, unit 28 - Describe health issues",[
            new("to put in / to insert / to add (object / reservation)", ["いれます", "入れます"], Tooltip.Iremasu),
            new("What’s wrong? / What happened?", ["どうしましたか"], Tooltip.Doushimashitaka),
            new("It hurts / painful", ["いたい", "痛い"], Tooltip.Itai),
            new("head", ["あたま", "頭"], Tooltip.Atama),
            new("neck", ["くび", "首"], Tooltip.Kubi),
            new("electricity / electric / light", ["でんき", "電気"], Tooltip.Denki),
            new("social media", ["えすえぬえす", "SNS"], Tooltip.SNS),
            new("almost / mostly / nearly all", ["ほとんど"], Tooltip.Hotondo),
            new("arm", ["うで", "腕"], Tooltip.Ude),
            new("to fall / to tumble", ["ころびます", "転びます"], Tooltip.Korobimasu),
            new("to hit / to strike / to bump / to get hit", ["うちます", "打ちます"], Tooltip.Uchimasu),
            new("wound / cut / injury", ["きず", "傷"], Tooltip.Kizu),
            new("pharmacy / drugstore", ["やっきょく", "薬局"], Tooltip.Yakkyoku),
            new("for a while / for some time", ["しばらく"], Tooltip.Shibaraku),
            new("to get better / to recover / to be fixed", ["なおります", "治ります"], Tooltip.Naorimasu),
            new("to paint / to apply / to spread", ["ぬります", "塗ります"], Tooltip.Nurimasu),

        ]),

        new("Section 3, unit 27 - Use past tense adjectives",[
            new("shelf", ["たな", "棚"]),
            new("husband", ["だんなさん", "旦那さん"]),
            new("wife", ["おくさん", "奥さん"]),
            new("entryway", ["げんかん", "玄関"]),
            new("to wear (lower body / feet)", ["はきます", "履きます"]),
            new("to wear (upper body / whole body)", ["きます", "着ます"]),
            new("whose", ["だれの", "誰の"]),
            new("gate", ["もん", "門"]),
            new("furniture", ["かぐ", "家具"]),
            new("between / space / interval / gap", ["あいだ", "間"]),
            new("vase", ["かびん", "花瓶"]),
            new("dining room / dining", ["ダイニング"]),
            new("handmade", ["てづくり", "手作り"]),
            new("wall", ["かべ", "壁"]),
            ]),

        new("Archive",[
            new("onion", ["たまねぎ", "玉ねぎ"]),
            new("sugar", ["さとう", "砂糖"]),
            new("potato", ["じゃがいも", "じゃがいも"]),
            new("wheat flour / flour", ["こむぎこ", "小麦粉"]),

            new("life / daily life", ["せいかつ", "生活"]),
            new("traditional flooring", ["たたみ", "畳"]),
            new("late / slowly", ["おそく", "遅く"]),

            new("to turn on / to attach", ["つけます", "付けます"]),
            new("to arrive / will arrive", ["つきます", "着きます"]),
            new("merch", ["グッズ", "グッズ"]),
            new("to go out / head out (outing/activity)", ["でかけます", "出かけます"]),
            new("to leave / to exit / to come out (general verb for exiting a place)", ["でます", "出ます"]),
            new("pay, going to pay, will pay", ["はらいます", "払います"]),
            new("enter/enroll/join", ["はいります", "入ります"]),

            new("many / numerous / a large number of", ["おおい", "多い"]),
            new("front desk", ["うけつけ", "受付"]),
            ]),
        new("Practice sentences",[
            new("We should get off at the next station.",["つぎのえきでおりましょう。", "次の駅で降りましょう。"]),
            new("My younger brother also enrolled at a university last year.",["きょねんおとうともだいがくにはいりました。", "去年弟も大学に入りました。"]),
            new("The office is on the tenth floor of the building.", ["オフィスはたてもののじゅっかいです。", "オフィスは建物の十階です。"]),
            new("I don't want to talk with the company people.", ["かいしゃのひととはなしたくないです。", "会社の人と話したくないです。"]),
            new("The nearby supermarket closes at six o'clock.", ["ちかくのスーパーはろくじにしまります。", "近くのスーパーは六時に締まります。"]),


            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
            //new("", ["", ""]),
        ]),
    ];

}
